### ISSUE TITLE
Disable Touch when slideshow is running

### ISSUE THREAD

**Issue by feutl** [mvysny/photocloud-frame-slideshow#101]
I am using Photocloud with an old Android tablet to give a family member a simple way to see what the family is doing.
So far everything is fine, but one thing bothers me and makes more problems than I expected, the Frame/Tablet is located at a quite prominent location.
Sometimes other family members (the little ones ;) ) touch the screen which makes it pause or jump out of the fullscreen mode (where taskbars ar hidden etc).

I would love to have the option, to disable the touch functionality or replace it by a looooooong touch to get to the menu.
It makes me sad, if the slideshow pauses because someone touched the screen and the older family member (above 70y) is unable to retain standard functionality again.

The workaround for now is, unplug and plugin in the powersupply again, but I would love to see a option to avoid this overall.

Thanks

**Comment by mvysny** [comment]
Haha, thanks for letting me know :) I was thinking about implementing a full-blown dotted lock screen, but long touch is probably more than enough. I'm thinking 3 second long touch would be more than enough, what do you think?

**Comment by feutl** [comment]
> Haha, thanks for letting me know :) I was thinking about implementing a full-blown dotted lock screen, but long touch is probably more than enough. I'm thinking 3 second long touch would be more than enough, what do you think?

Why not make it adjustable?
Give Options like, Disable, 3 sec, 5sec 10 sec
This would allow anyone to choose what they expect to be the best choice for them.
Otherwise I would opt for 3sec :)

**Comment by mvysny** [comment]
Sounds good!

**Comment by mvysny** [comment]
Implemented in 1.13.7. Head to `Settings / Screen / Screen lock` and set it to 3 seconds :)

**Comment by feutl** [comment]
testing it as soon as I have access to the devices. I give some feedback afterwards.

**Comment by mvysny** [comment]
Oh, the feature hasn't been released yet. I'm thinking of implementing #61 first.

**Comment by feutl** [comment]
I know, I am just waiting until it happens ;) and give you feedback. No worries

**Comment by feutl** [comment]
I could not test this feature on my main photoframe tablet because it is running 4.1
It seems to work on my mobile, but this is not really a real life scenario there :)
