### ISSUE TITLE
Increase Cache Size available device storage

### ISSUE THREAD

**Issue by feutl** [mvysny/photocloud-frame-slideshow#102]
I am using old tablets and SoC devices dedicated for photocloud, They are connected to monitors or as a tablet being standalone.
All of this devices have actually lots of internal storage available, form 8GB to 32GB, in my case.

The users of my nextcloud instance, also used for photocloud, move pictures in and out of different folders used with the photocloud devices. In all of this cases, they use the full-size images from their mobile phones or even their dedicated cameras.
No one is resizing them upfront, therefor the max. 2GB space is allocated more often than I thought. This, automatically puts more load on the internet connection of the hosted nextcloud instance and the local internet connection where the photoframe is being used.

I would like to see an option to increase the cache usage to the maximum available space on the device itself. This is done by lots of streaming/move apps for offline content storage. The device itself has the space, the pictures do not need to be re-downloaded because of "saturated" cache space, and this helps to save internet bandwidth usage, and also allows the device to stay offline for some time, but show pictures.

**Comment by mvysny** [comment]
Sounds good, I'm thinking of adding the following options:

* 3 GB
* 5 GB
* 10 GB
* Use all available space minus 128 mb for the system and to lower the fragmentation

**Comment by feutl** [comment]
sounds great 👍

**Comment by mvysny** [comment]
Implemented in 1.13.7

**Comment by feutl** [comment]
I am giving feedback as soon as I do have time and get access to the devices running photocloud.

**Comment by feutl** [comment]
I tested this option on my odroid running 4.4 and it seems to work quite fine :)
My tablet I am using is running on 4.1 which is not getting any updates at all any more.

thanks
