### ISSUE TITLE
Support for older Android devices

### ISSUE THREAD

**Issue by feutl** [mvysny/photocloud-frame-slideshow#105]
Getting old Android tablets and use them as a photoframe with photocloud-frame is very easy, but those 20$ second hand tablets are using 4.x androids. In my case I have 2 tables with 4.1 and one with 4.4
Is there a way to get the latest version ported to 4.1 as well, or are there any technical reasons why 4.4 is the "oldest" supported version ?

Another option I could live with, is just downloading the apk and installing it manually, if this is technically not restricted by the app.

**Comment by mvysny** [comment]
Unfortunately that's because the android device fragmentation. The READ_EXTERNAL_STORAGE https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE works properly starting from Android 19; on lower devices even though PhotoCloud declared a requirement for READ_EXTERNAL_STORAGE there would still be devices that would crash that the READ_EXTERNAL_STORAGE is missing :(

**Comment by feutl** [comment]
ok thanks, makes sense.

Would it be possible to install the latest APK and install it manually on the device?
I am not using "External Storage" or is every storage "external" if it is not the system itself?

thanks

**Comment by mvysny** [comment]
Unfortunately that depends on the particular device and its policies (including security policies). Regarding the APK manual install - I think that the adb tool will complain, but I can test this in the Emulator.

**Comment by feutl** [comment]
no worries, I test that on my own, if it is not working I install the "old" version from the play store again and setup the nextcloud account. not that hard.
I give you feedback as soon as I had time to do this.

**Comment by mvysny** [comment]
I've added a link to the unofficial build to the [FAQ / Supported Android Versions](http://www.android-photo-frame.eu/faq.html#supported-android-versions), please try it out :+1:

**Comment by feutl** [comment]
I will do - over christmas :)
THANKS

**Comment by feutl** [comment]
forgot to report back, sorry, but works just fine :)

**Comment by mvysny** [comment]
Awesome, good to hear that :+1:
