### ISSUE TITLE
Mega integration with the official SDK

### ISSUE THREAD

**Issue by luislobo** [mvysny/photocloud-frame-slideshow#106]
As suggested in https://groups.google.com/forum/#!topic/photocloud-frame/dE9iUQLx8Fk, I'm opening this issue here.

I have not been able to login using Mega, throwing a silly exception.

Would you consider implementing the official SDK, to see if it works that way?

Thank you very much!

**Comment by mvysny** [comment]
Could you paste the exception here please? Maybe it could be something which is easy to fix.

**Comment by luislobo** [comment]
![Screenshot_20190426-075152](https://user-images.githubusercontent.com/453120/59848935-fd0ee780-932b-11e9-9368-37ac71d28b37.png)

**Comment by luislobo** [comment]
Any news about this one?

**Comment by mvysny** [comment]
The Mega SDK is here: https://github.com/meganz/sdk

**Comment by mvysny** [comment]
The official SDK is working properly, I'll try to integrate it with PhotoCloud.

**Comment by luislobo** [comment]
@mvysny thank you very much!

**Comment by mvysny** [comment]
Implemented the Native Mega client. The old Java one is still used by default, but now you can configure which client to use when creating the Mega stream.

It is not recommended to switch a client and having an existing Mega stream. To switch client, remove the old Mega stream, add the stream anew and choose the new client type in the "Add Mega" activity.

Implemented in PhotoCloud 1.13.9

**Comment by luislobo** [comment]
@mvysny Thank you so much! I'm about to update it
