### ISSUE TITLE
not connected to the broadband internet stopping

### ISSUE THREAD

**Issue by nascentt** [mvysny/photocloud-frame-slideshow#108]
I've started getting the error 'not connected to the broadband internet stopping' when I try to use the app without internet. did something change in an update?  I specifically bought and use this app due to the ability to use smb shares in my network when offline.

https://groups.google.com/forum/#!topic/photocloud-frame/ziLyazD1BuE

**Comment by mvysny** [comment]
There was no update which would touch this functionality - it was always like this. It is a protection mechanism that doesn't start the slideshow if the wifi is not on, to save your money and prevent downloading images over an unmetered connection.

However, it is true that the protection mechanism doesn't work as expected. Currently it only checks for a WiFi being on; if it's off then it assumes you would be downloading the data over a metered connection. That is wrong for the following reasons:

* If you're offline, the cache kicks in and shows cached images; so no internet usage.
* If you're using unmetered GSM (flat data package)
* Some WiFis are in fact metered, e.g. if you're connected to an AP provided by a phone with metered GSM connection.

The algorithm should therefore instead check if there is an active metered internet connection present.

As a workaround, please disable the "Check WiFi Connected" configuration option.

**Comment by mvysny** [comment]
Fixed in 1.13.9. The "Slideshow" button will now offer three options if an unmetered connection is not available:
1. Yes - start slideshow as usual, possible data charges will occur
2. No - don't do anything
3. From cache - show images from cache.
