### ISSUE TITLE
Can't connect to OneDrive Business

### ISSUE THREAD

**Issue by Gedhe76** [mvysny/photocloud-frame-slideshow#109]
Hi,
When I try connect PhotoCloud Slideshow to OneDrive Business (is part of office365 premium subscription) is coming error like in below picture. Any Idea how to fix this?
![image](https://user-images.githubusercontent.com/5371084/61506907-43806080-aa16-11e9-8ea2-602573092b0a.png)

Cheers,
Gedhe ND

**Comment by mvysny** [comment]
Hi, from the error message it sounds like the administrator of your domain manlogistics.com.au needs to enable PhotoCloud as a registered application which is allowed to access your files.

**Comment by Gedhe76** [comment]
Thank you for your response, We are using Microsoft Exchange Server on line . Do you have some instruction to enable PhotoCloud as registered application ?

**Comment by mvysny** [comment]
Unfortunately I have no such instructions. I'd suggest to contact the Microsoft support line which is supposed to answer questions like this.

**Comment by Gedhe76** [comment]
Ok, I will do your suggestion. Thank you for review.

**Comment by mvysny** [comment]
Thank you. If you find a solution, would you please attach it here, so that others would benefit from your findings?

**Comment by Gedhe76** [comment]
Hi,
We are a paid PhotoCloud and using username "jackmrush@gmail.com". We are having a problem setting PhotoCloud with our Onedrive Business account.
When we log in using our Onedirve's username and password , we get this error message
![image](https://user-images.githubusercontent.com/5371084/62099635-5110d280-b2c1-11e9-897a-986e34f22b4d.png)

We went to MS Support and confirmed that the setting on our Azure server are all corrected but the problem still happen.
Could you please confirm that Photocloud is support to run with Onedrive business account?
to be more technical
Could you please confirm that
Does PhotoCloud support an in-app API experience to make calls to the Microsoft Graph and get access token from Azure AD?
and any suggestion if the answer of above question is yes.

Cheers,
Gedhe ND

**Comment by mvysny** [comment]
I am using the official OneDrive API for Android which comes from https://github.com/OneDrive/onedrive-sdk-android . I'm using the older version of 1.2.2 since I've modified a couple of classes to allow silent login: https://github.com/OneDrive/onedrive-sdk-android/issues/49 . Because of those workarounds I can't use the newest version 1.3 until Microsoft implements support for silent login.

Anyway, I have added the redirect URI into the PhotoCloud registration page at https://apps.dev.microsoft.com , please see the screenshot attached. I'm going to test whether the client still works okay.

**Comment by mvysny** [comment]
Regardless of the outcome: if we are unable to make this work, just let me know your Google Transaction ID of your purchase and I'll refund.

**Comment by mvysny** [comment]
I've verified that with my Personal account PhotoCloud still works properly. Unfortunately I have no way of testing with OneDrive Business Account, for the very simple reason that I don't have access to any Business account myself. Microsoft doesn't provide means of opening a testing business account either. Therefore, unfortunately I can't test your use-case. I was under an impression that the API is the same for accessing photos on personal account and on a business account, but if that's not the case then there's unfortunately not much I can do.

Just let me know if you'd like the refund.

**Comment by Gedhe76** [comment]
Hi,
I think we are almost there, can you tell me what is the ReturnURL we should put in our Azure Active Directory App setting, please?

**Comment by mvysny** [comment]
Of course, the return URL is `photoframeocloud7c99e15ae08f11e6a593d33144826c5e://oauth`

**Comment by Gedhe76** [comment]
Hi,
I try to put the return Url in the Azure AD but still can not fix this issue. I am just stuck in here.

**Comment by mvysny** [comment]
Unfortunately I'm very sorry but I do not have the resources (access to OneDrive Business account) to help you. If anyone other managed to run PhotoCloud with OneDrive Business, please share the necessary steps here.

@Gedhe76 please paste your transaction ID here to get a refund.

**Comment by Gedhe76** [comment]
Hi Martin,
I have solve this issue. We now using an app call "SkyFolio for Onedrive" in Android and working to connect Onedrive business. Now we can do slideshow our Photo Gallery that save in OneDrive for Business. 

For now no need to refund what we have to pay to you as maybe in the feature we back again using Dropbox for our Photo Gallery and use again your "PhotoCloud Slideshow" app.

Thanks anyway for your reply and discussion.

Regards,
Gedhe ND

**Comment by mvysny** [comment]
Thank you for letting me know, and I'm sorry I was not able to solve this issue for you. I'm happy that SkyFolio is working for you well.

Best regards,
Martin
