### ISSUE TITLE
Order of slides needs to be predictable

### ISSUE THREAD

**Issue by AlBro72** [mvysny/photocloud-frame-slideshow#110]
I have a small collection of jpg's in a WindowsShare that I need to show in a certain order.
I am powering up a RikoMagic MK802IV which Autolaunches this Photocloud App and then reaches out to this Windows Samba share and starts scrolling though the jpg's.  I need control over the order of my slideshow. The best would be to do that by how they are named (alpha-numeric order??)
Can the option to do this please be added soon.

Thanks

**Comment by mvysny** [comment]
The setting "Slideshow / Random Order" will now also control the ordering of slideshows started via the "SLIDESHOW" button on the slideshow card. Fixed in PhotoCloud 1.13.9

**Comment by AlBro72** [comment]
Pardon my ignorance, but has the new build been posted to the Google Play Store?
How do I update from v1.11.6

**Comment by mvysny** [comment]
Ah, apologies, you have to have Android at least 4.4 (API level 19) for the newest version. Bugs originating from The Android fragmentation were just too many, and Android 19 fixed lot of those, that's why I decided to only use that version.

**Comment by AlBro72** [comment]
OK thanks

I will have to see if my Rikomagic IV can be updated from 4.2.2 to 4.4.

Al.

**Comment by AlBro72** [comment]
OK great

I got my device updated to Android 4.4 and am running your latest build. (I had to totally reinstall everything from the Play Store)

I have another problem which I think started even before this latest update.
I get this when I try to access the SAMBA share I am using:
I tried replacing the IP address with text but still it errors like this now.
Did something change on my end?

Thanks

Al

[cid:image001.png@01D54795.ABB3BC80]

**Comment by mvysny** [comment]
Hi, I can not see the image unfortunately, could you attach the image via the GitHub tracker at https://github.com/mvysny/photocloud-frame-slideshow/issues/110 ?

**Comment by AlBro72** [comment]
It is an error message that pops up overnight.

“Failed to connect to smb://192.168.4.13/logging/slides/: java.lang.RuntimExceptoin: Plain text passwords are disabled”

This is after everything was working just fine for a few days.
I wonder what this could mean?  I don’t think anything changed with my windows share.

Al

**Comment by mvysny** [comment]
Hmm, there could be a lot of changes between PhotoCloud 1.11.6 and 1.13.9. The 1.13.9 uses the `jcifs:jcifs:1.3.17` library to access Samba; unfortunately I do not have access to the sources of the old version anymore, so I do not know which Samba library that one used.

What kind of storage are you accessing via Samba? It could be that there has been a change in the configuration. However, please open a new bug report regarding this.
