### ISSUE TITLE
Pictures extensions in UPPERCASE not recognized ?

### ISSUE THREAD

**Issue by JHAres** [mvysny/photocloud-frame-slideshow#111]
Hi Martin,
Just a couple of lines to say thanks for your app, it's great so I got the "no ad" version... Nice...!!!
Besides that, seems to have a little glitch, the pictures with upppercase extension (i.e. "JPG" instead of "jpg", "PNG" instead of "png") are not recognized/decoded in the first view, the folder view (but works ok in slideshow)...
Let me know if you need some clarification and/or betatesting.
Kind Regards...!

**Comment by JHAres** [comment]
![Screenshot_20190911-130217_PhotoCloud Slideshow](https://user-images.githubusercontent.com/55200949/64714494-1d66c200-d495-11e9-9291-5faa7e015ae0.jpg)

**Comment by mvysny** [comment]
Thank you very much for your kind support, and I'm sorry for the bug. Let me take a look at it :)

**Comment by JHAres** [comment]
Don't worry...!!!
let me know if I can help... :-)

**Comment by mvysny** [comment]
Thank you for your offer, but this case is luckily easy to reproduce and to fix :)

Fixed in 1.13.10
