### ISSUE TITLE
Hide Error Messages - Toggle Setting

### ISSUE THREAD

**Issue by theQuicker1** [mvysny/photocloud-frame-slideshow#113]
Similar to issue #64 can you please add a setting for ignoring all error messages?

Instead of showing an error for photos or other files that do not load, just skip to the next picture.
Thanks!
![Screenshot_20190913-095744](https://user-images.githubusercontent.com/34199441/64888996-22587c80-d621-11e9-89ed-cf413b66d5b6.png)

**Comment by mvysny** [comment]
Sounds like a good idea, thank you. The slideshow stops at fatal issues such as invalid user name / password, but corrupted photo should not be considered fatal.

**Comment by mvysny** [comment]
Fixed in 1.13.10, there is a new setting "Skip Corrupted Images" (by default set to true) which suppresses such "Unknown error loading bitmap"
