### ISSUE TITLE
Photocloud does not recognize some jpegs as photos

### ISSUE THREAD

**Issue by wesf99** [mvysny/photocloud-frame-slideshow#114]
Photocloud recognizes jpegs from phone as photos but not jpegs taken on my Sony camera. I get the message xxxxx.jpg is not an image, cannot show.

![DSC00137 (2)](https://user-images.githubusercontent.com/55278725/64900625-b4fe2780-d6c4-11e9-8f0c-5b9fd73eff46.JPG)

**Comment by mvysny** [comment]
Thank you, this is a duplicate of #111 which has been closed recently. Please wait a couple of days and I'll release a new version.
