### ISSUE TITLE
Samba connection error

### ISSUE THREAD

**Issue by rajdude** [mvysny/photocloud-frame-slideshow#115]
Hello, Samba server connection is giving me an error. Pasted below. Looks like it's trying to connect to the correct machine, because the IP address is showing up in the error message, and that IP address is correct.

Any tips on how to resolve this?
By the way, is there any way to enter credentials of the network share?

![Screenshot_20190916-103532](https://user-images.githubusercontent.com/44186620/64966949-bb7bd300-d86d-11e9-9898-b8479e24a83c.png)

**Comment by mvysny** [comment]
Hi, the java.net.SocketException: Connection Reset suggests that Samba is not running on 10.1.1.50, or there is a firewall or something like that. SocketException: Connection Reset means that a TCP connection cannot be made, which is needed for connect to any server. Please try other Samba software to connect from your phone, e.g. ES File Explorer.

After the connection is successfully made, PhotoCloud will ask for username/password if they are needed.

**Comment by rajdude** [comment]
Hello Martin, thanks for responding. I am able to connect to the server using samba if I use another app like file manager +. Check screenshot below...

**Comment by mvysny** [comment]
Hmm,. that's weird. Could you try to connect to an IP address of the server (judging from the logs it's 10.1.1.50) instead, both from photocloud and the other app? This can rule out some weird dns hostname-to-ip resolution.

**Comment by rajdude** [comment]
Ok I just tried that. Got an error. Please see screenshot attached...



-Raj
(Sent from my cellphone)

Get BlueMail for Android<http://www.bluemail.me/r?b=15635>
On Sep 16, 2019, at 11:49 PM, Martin Vysny <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm,. that's weird. Could you try to connect to an IP address of the server (judging from the logs it's 10.1.1.50) instead, both from photocloud and the other app? This can rule out some weird dns hostname-to-ip resolution.

**Comment by rajdude** [comment]
![Screenshot_20190917-130414](https://user-images.githubusercontent.com/44186620/65252998-e497a000-dac7-11e9-98d7-5b4fe0d63143.png)

Sorry, here is the screenshot.
It didn't make it to this thread when I emailed it

**Comment by mvysny** [comment]
Still SocketException - Connection Reset. I wonder if it is because of some weird TCP/IP firewall settings, or whether I'm packing too old jcifs library. Unfortunately it's not easy to upgrade, see #100 for more details.

**Comment by mvysny** [comment]
A new Samba client has been implemented. Please try out PhotoCloud 1.13.18 once it's released. Closing.

**Comment by rajdude** [comment]
ok thanks Martin. When is 1.13.18 going to be released?
I still have 1.13.17 .
