### ISSUE TITLE
Enhance fullcreen-zoom

### ISSUE THREAD

**Issue by Dax88** [mvysny/photocloud-frame-slideshow#116]
Hi, perhaps it is possible to enhance the zoom in fullcreen-mode? I use a 10'' 16:9 tablet in landscape orientation. Most pictures are 3:2, so they have a black bar on the left and right. 
It woud be great to have an option to zoom the pictures to the full wide (but keep the aspect ratio and crop the pictures on top and bottom).

**Comment by mvysny** [comment]
Sounds good! I'll add the setting for that. However, when you pause the slideshow I think it's best to show the photo in its entirety (zoomed out); once you resume slideshow the pictures will be cropped again.

**Comment by mvysny** [comment]
Fixed in 1.13.10
