### ISSUE TITLE
Settings Screen misalligned on Android TV

### ISSUE THREAD

**Issue by feutl** [mvysny/photocloud-frame-slideshow#117]
I am using version 1.13.10 on my Mi Box running Android TV and the Settings screens get cut off on the edges of the screen.
Half of the first letters are hidden behind the frame of my screen ;) I can assure this for the left an right edge, most properly the same accounts for top and bottom screen.

At the main screen I am not quite sure because of the available free space, but I do know that the slideshows are also get cut by a few pixels on all edges.

Can I provide you with some more details ? Please, tell me how and what I can do ?

**Comment by mvysny** [comment]
Ah damn, that's actually pretty standard thing on most TVs - the overscan effect: https://developer.android.com/training/tv/start/layouts#overscan
It doesn't happen on my TV so I thought Android takes care of this. I'll add the margin to the settings activity. Thanks for letting me know :)

**Comment by mvysny** [comment]
Fixed in PhotoCloud 1.13.11

**Comment by feutl** [comment]
awesome :) btw I am using a Xiaomi Mibox3 just for reference
