### ISSUE TITLE
Cannot remove data and folder display during slideshow

### ISSUE THREAD

**Issue by ShannanHeinitz** [mvysny/photocloud-frame-slideshow#119]
Cannot remove data and folder display at bottom during slide show. I assume turning off show exif data should do this but it doesnt.

Am using Samsung Galaxy 7

**Comment by mvysny** [comment]
When I turn off `Settings / Widgets/HUD / Show Clock` and `Settings / Widgets/HUD / Show Weather Forecast` and `Settings / Widgets/HUD / Show EXIF in Slideshow` and `Settings / Widgets/HUD / Show photo file name`, all bottom widgets will disappear and there is nothing obscuring the photo. Could you please try turning off all of the abovementioned settings?

**Comment by ShannanHeinitz** [comment]
I had the Show Clock still on. I had overlooked the settings when I tried before .Thank you.

**Comment by mvysny** [comment]
Thanks for letting me know, great that we managed to solve this issue. I think the "Show Picture Only" setting would duplicate the effect of disabling all of the widgets, so I'm hesitant to implement that. Instead I propose to document this in the http://www.android-photo-frame.eu/faq.html

**Comment by mvysny** [comment]
Done - the info should be in the FAQ section.
