### ISSUE TITLE
Crossfade at 5 seconds length

### ISSUE THREAD

**Issue by ShannanHeinitz** [mvysny/photocloud-frame-slideshow#120]
Crossfade at 5 seconds is not working properly, causing abrupt change and the end of the cross fade. 3 seconds works well .

I am using Samsung galaxy S7

**Comment by mvysny** [comment]
Hi, unfortunately I failed to reproduce the issue. I've set Settings / Slideshow / Slideshow Delay to 5 seconds and started the slideshow of my phone's Gallery. The photos are cross-faded properly: there is no abrupt change, the cross-fade is smooth and fades in next image fluently.

Could you please try the Gallery Slideshow, whether the issue persists? Could you please list which slideshows cause the issue? Ultimately, could you shoot a video of the abrupt slideshow change?

**Comment by ShannanHeinitz** [comment]
Try making the delay between images was at 3 seconds while having the cross fade at 5 seconds. 

In hindsight this seems like a obvious cause for abruptness, but as I was new to the software, there was nothing indicating the conflict as I was still learning the settings and had overlooked the 3 seconds setting. 

I would still consider the abrupt change a bug, but the solution would to either max out the fade duration to transfer duration, vice versa , and/or inform user of the conflict.

Regards.

**Comment by mvysny** [comment]
Thank you. I agree, the app should definitely prevent such situation. Let me think on the best way to tackle this.

**Comment by mvysny** [comment]
Fixed in 1.13.16. The app will still allow you to shoot yourself in the foot, but a warning toast will now be displayed :)
