### ISSUE TITLE
Adding filter to show only horizontally or vertically taken photos

### ISSUE THREAD

**Issue by TrickyTrix** [mvysny/photocloud-frame-slideshow#121]
I usually add a bunch of photos (1000+) to show randomly, but since my screen is mounted horizontally it would be nice if the app would have an option to filter and show only horizontally (or vertically) taken photos.
What do you think about adding an option to show only horizontally (width > height) or vertically (height > width) taken photos?

**Comment by mvysny** [comment]
Thanks! This should be doable, but let me take a look first, before making any promises :)

**Comment by mvysny** [comment]
Implemented in 1.13.16. To enable, head to `Settings / Filters/Moments / Filter on Image Size` and set it to "Landscape Only" or "Portrait Only".
