### ISSUE TITLE
UI lock for seniors/child usage

### ISSUE THREAD

**Issue by gemfor** [mvysny/photocloud-frame-slideshow#126]
I would like to use the app as remote frame for my 90+ old family members that I'm not able to visit due to Covid. I'm afraid that they will stop or misconfigure the app during handling the tablet. I would like to  ask for implementation of slide-show lock like other apps are using e.g. [Toddler Lock ](https://play.google.com/store/apps/details?id=marcone.toddlerlock)

**Comment by mvysny** [comment]
Hi, could you please try settings / screen / screen lock?

**Comment by mvysny** [comment]
Possibly a duplicite of https://github.com/mvysny/photocloud-frame-slideshow/issues/101

**Comment by gemfor** [comment]
Works great!
