### ISSUE TITLE
Night mode enhancement

### ISSUE THREAD

**Issue by gemfor** [mvysny/photocloud-frame-slideshow#127]
I have an issue using the app on Lenovo M10 tablet in shared hospital room. I set night brightness to minimum but still there are complains about disturbing other people in the room during the night. 
I suggest adding one more step to brightness scale that would ideally switch the screen off completely or at least it will set brightness to minimum and keep playing all black picture (or mix the picture played with black) to reduce emitted light even more.

I know you have a plan to have some sort of night sleep mode, but I don't need full sleep. Just the emitted light is the issue.

Thanks

**Comment by mvysny** [comment]
There are settings regarding this, in photocloud settings / screen / brightness, and you can set the back light brightness to as low as 0. However I just tried that on my phone and it wouldn't work for some reason. Let me take a look at it.

**Comment by mvysny** [comment]
I just debugged the issue: PhotoCloud is setting `WindowManager.LayoutParams.screenBrightness` to 0.1f yet Android simply ignores that. Or, to be precise: setting the brightness to 1f (full 100%) works, setting the brightness to 0.1f doesn't work, as if only the increase of the brightness worked, but the decrease of the brightness wouldn't work :thinking: wtf... investigating further.

**Comment by mvysny** [comment]
Reported as a bug to Android bug tracker, let's wait and see: https://issuetracker.google.com/issues/37822816

For me the following workaround worked:

1. Go into your phone's settings, display, and disable the adaptive brightness (or automatic brightness or so).
2. Then, still in the phone's settings, display, set the brightness level to 0 (minimum).
3. PhotoCloud should now be able to correctly control the brightness since it will always increase the brightness from the system settings baseline.

**Comment by gemfor** [comment]
Suggested workaround doesn't work on Lenovo M10 with Android 9 (tested both screensaver and normal mode). Could you please implement brightness control workaround by tweaking picture brightness / fade out and using black picture for 0%. I know it's not perfect for IPS screens but it will work great on OLED displays.

**Comment by mvysny** [comment]
Sure! You can set the background color to black via `Settings / Slideshow / Photo Slideshow Background`. I'll also implement the artificial picture dimming (you'll be able to pick from 0% dimming - no dimming to 100% - full dimming), it's actually easier than it sounds.

**Comment by mvysny** [comment]
Are you perhaps using Daydream? I just noticed that the brightness is not controlled during the Daydreaming.

**Comment by mvysny** [comment]
Implemented in 1.13.17

**Comment by gemfor** [comment]
I'm using Daydream as well as normal mode. I will check 1.13.17 later today and will let you know.

**Comment by mvysny** [comment]
Ah, the release is not yet ready, but I'll push it out later this week.
