### ISSUE TITLE
Slideshow Ordering Enhancement, Feature Request

### ISSUE THREAD

**Issue by andyfrei** [mvysny/photocloud-frame-slideshow#128]
Hey there 
regarding the ordering of the medias in the slideshow, I can see A-Z and random. Is there any option to sort by date taken/date original or even better sort by date taken, if that date is not present use date of creation or last changed date to sort the slideshow?
Cheers   ##Andy

**Comment by mvysny** [comment]
Hi Andy, if you start the slideshow from the FileSystem browser, then the slideshow will attempt to order the photos in whatever order is currently configured in the FileSystem Browser. There is a button in the upper-right corner for sorting, by default it reads `AZ^` but it can be changed to "Sort by date created"; slideshow launched from the browser will then honor this setting.

Is this acceptable please?

**Comment by mvysny** [comment]
> the slideshow will attempt to order the photos

The problem are nested folders - PhotoCloud could either scan a complete folder structure, then sort the files, then start showing the slideshow, but that could potentially cause a huge initial delay. Therefore I've used an alternative approach to start the slideshow as soon as possible, showing photos from the root folder first, even if there is a newer photo in the subfolder.

**Comment by andyfrei** [comment]
What a great and quick person!!!

**Comment by mvysny** [comment]
Thank you ;)
