### ISSUE TITLE
more then one slideshow per connector

### ISSUE THREAD

**Issue by andyfrei** [mvysny/photocloud-frame-slideshow#132]
I'd personally would like to save several slideshows with the same connector.

For example Google Photos:
one "standard" gallery for all pics from 2020 as the autostart gallery.
but also from another specific album I'd like to just activate a slideshow - from the last holidays as an example - when needed, but have the autostart gallery/slideshow untouched.

Therefor I could just add another gallery/slideshow when needed, instead of having to configure a new one and then reconfigure back to the standard one...

**Comment by mvysny** [comment]
Hi, that's a great idea! I'm thinking of adding a "clone" button to every Stream which would create a clone of that Stream. You can then root that clone in a folder (e.g. your last holidays folder) and start slideshow for that clone, then delete it once it's not needed.

Would that work?

**Comment by mvysny** [comment]
I've implemented this feature in 1.13.17, please give it a go :+1: I'll release shortly.

**Comment by andyfrei** [comment]
Works great on my end!
