### ISSUE TITLE
Daydream purchase not reflecting

### ISSUE THREAD

**Issue by goblygoop** [mvysny/photocloud-frame-slideshow#133]
Purchased daydream not registering

I have the true in app, true nag (what's the nag?), False daydream.

What info do you need?

**Comment by mvysny** [comment]
Could you check in Google Play which subscriptions you have purchased? It could be that you accidentally purchased "Remove Nagging Screen" instead of "Daydream". Also please see http://www.android-photo-frame.eu/faq.html for more information.

**Comment by goblygoop** [comment]
My fault it seems.  I went to "purchase daydream" and it gave me the anti nagging which is useless to me.  I just want daydream on

**Comment by mvysny** [comment]
No problem :) If you wish to refund, just send me the transaction ID to martin@vysny.me

**Comment by goblygoop** [comment]
Thanks, but keep it.  I'll just contribute to you as a developer and for responding :)  Suggestion would be to make that setting easier to understand.  I tried to purchase daydream on Android TV (Nvidia Shield),  but got nagging screen removal for $3.50.
