### ISSUE TITLE
Unable to add Windows share

### ISSUE THREAD

**Issue by stncrn** [mvysny/photocloud-frame-slideshow#135]
Hello

When trying to add a Windows share source, I get the following error, as soon as the 'add windows (samba) share' view opens:

![Screenshot_20200813-120747](https://user-images.githubusercontent.com/25079376/90122646-e3b1d180-dd5d-11ea-988e-aca94e8f1835.jpg)

The error is not going away, whatever I do (adding server name and clicking the arrow, or clicking the reload button)

I tried to add the share using:
- GAME
- GAME/share
- stan@GAME
- stan@GAME/share
- 192.168.1.26
and the error stays here, like what I've written wasn't taken into account.

I checked my Windows 7, and both the Smbv1 and Smbv2 protocols are activated.

I also tried the app on my Nvidia Shield, and the issue is exactly the same.

Note that both devices (phone and androidtv) are able to access this share with other apps (fx explorer)

App version is PlayStore's latest, I discovered your app only today.

Regards

**Comment by mvysny** [comment]
Thank you for letting me know. Let me investigate which samba client does the fx explorer use. Is FX Explorer perhaps open-source so that I can peek inside and check which exact version of samba client are they using?

**Comment by mvysny** [comment]
Also see #100 - unfortunately it's not easy to find a samba client library that just works.

**Comment by mvysny** [comment]
Thank you for your patience. A new Samba client has been implemented which should work much better with Samba shares. Closing this as duplicite of #141
