### ISSUE TITLE
Feature request - optional background image

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [mvysny/photocloud-frame-slideshow#136]
Just bought your app + daydream option for my Android TV.  Good app, working well so far, thanks!

I have a simple feature request - can you please consider implementing an optional background image (rather than just colour) – with photos displayed over the top of this.  Would be cool, for instance, to take a photo of the wall that the TV is mounted on & have that as the background.  Especially good for 4:3 pics on 16:9 TV

Thanks!

**Comment by mvysny** [comment]
Let me try :+1: This does increase the risk of running OutOfMemory a bit, but there's no way to find out except trying :-)

**Comment by mvysny** [comment]
Implemented in 1.13.18

**Comment by TheOriginalMrWolf** [comment]
Awesome - thanks!! 👍

**Comment by mvysny** [comment]
Unfortunately I can't release new version because of Google: see #145
