### ISSUE TITLE
Add background music option

### ISSUE THREAD

**Issue by wwwescape** [mvysny/photocloud-frame-slideshow#14]
Add background music option. Not sure the best way we could define a source for the music, though.

**Comment by mvysny** [comment]
I'd propose to start really simple - one could simply choose one music file (a mp3) present locally in the phone/tablet, and that file would just be played endlessly in a loop. What do you think?

**Comment by wwwescape** [comment]
I agree! Let's start really simple.

**Comment by mvysny** [comment]
Implemented in 1.7.38.
