### ISSUE TITLE
Feature Request - slow scroll of panorama pictures

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [mvysny/photocloud-frame-slideshow#140]
Hi again!

Another feature request - would be great if panorama photos (any photos with aspect ratio wider than display device) had the option to be displayed full height, and then slowly scrolled from (say) left to right over the duration of the image display setting (rather than current behaviour which is showing solid colour bars above & below).

What do you think?

Thanks!

**Comment by mvysny** [comment]
Maybe try the Ken Burns effect? #67 

However it can not be customized currently: #74 ; perhaps a simple customization of the Ken Burns effect could allow you to have such a scrolling that you requested?

**Comment by TheOriginalMrWolf** [comment]
Hi,

Actually I see this as an 'overlay' feature specific to panoramas which works regardless of effect chosen (ie replaces the effect between transitions).  Sort of 'special handling' for panoramas if you like.  Panorama detection could be quite simple - if the photo's not 4:3/3:4 or 16:9/9:16 (maybe within a bit of a range), then it's a panorama...

For example, I would like to do simple fades from photo to photo - but if there's a panorama in the mix then (once it's faded in) it should start scrolling before finally fading out to the next photo.

This could also apply to vertical panoramas as well :)

What do you think?

**Comment by mvysny** [comment]
I've implemented the panorama scroller in 1.13.18; please try it out once the new version of PhotoCloud is out, and let me know whether it works for you.
