### ISSUE TITLE
Feature request: Display embedded jpeg in dng files (instead of converting) [$15]

### ISSUE THREAD

**Issue by rajdude** [mvysny/photocloud-frame-slideshow#142]
Hello Martin,
Good work here!

**I would like to request a new feature please:
It would be very nice if PhotoCloud could display the embedded jpeg preview image inside every dng raw image file.** 

I know PhotoCloud uses Libraw to show dng...but it seems to me that there is a conversion process happening (using libraw) ...that is why it takes a long time for PhotoCloud to show a dng on screen.

If PhotoCloud would simply read and display the embedded jpeg already available inside the dng file, it may be able to show the dng image on screen almost immediately.

PS: how can we put a "bounty" on this feature request?

**Comment by mvysny** [comment]
Hello, I'm not sure whether libraw allows access to the embedded jpeg, but I'll investigate.

However, if you're using Android 7 or higher which is able to load raws natively, then PhotoCloud no longer uses libraw. Please find more info here: https://github.com/mvysny/photocloud-frame-slideshow/issues/34#issuecomment-327527656

**Comment by mvysny** [comment]
I've found an API that seems to be able to extract the thumbnail from the image: `Libraw.getThumbnail()`, therefore it just might be possible. Could you please attach an example zipped dng raw image with a thumbnail, so that I can test the fix?

To open a bounty, please click the "Post Bounty" button at https://www.bountysource.com/ and post the link to this ticket.

**Comment by rajdude** [comment]
Sure Martin,
Here is an dng image which I use for definitely checking what any image viewer is doing.

- If it is converting dng, it will show a black image
- If it is showing the embedded jpeg inside dng, it will show a teddy bear.

Please see screenshots below.

![dng1](https://user-images.githubusercontent.com/44186620/98165152-62c52a80-1eb3-11eb-8235-9f4d6eb3c450.jpg)

![dng2](https://user-images.githubusercontent.com/44186620/98165162-66f14800-1eb3-11eb-9706-97a433c9abd1.jpg)

Actual dng file is attached here:


(oops, it does not let me attach a dng),,,,,any other way I can send you the dng?

**Comment by mvysny** [comment]
Please place the dng file in a zip archive, then attach the zip archive here.... yeah, I know, but github has this kind of limitation.

**Comment by rajdude** [comment]
oh, that is a simple solution...why did it not occur to me! :-(
Here you go...

oops, problem again...10 mb limit...my file is 34 MB...hold on, let me put it on a filesharing site...

**Comment by rajdude** [comment]
here you go

https://1drv.ms/u/s!AnyjWmU28erbm-U3ly4gqEVNCTK6Ow?e=XTPDtH

**Comment by mvysny** [comment]
Thank you for finding the workaround :) :+1: I have the file now; I'll try to get to this this week.

**Comment by mvysny** [comment]
Which Android version are you using please? I'm asking since Android 7 can load the raws natively, and it should work really fast. PhotoCloud therefore never uses Libraw on Android 7+, but if you're using a newer Android and you're getting slow decoding speeds, then I need to add a setting to use Libraw regardless of Android version.

**Comment by rajdude** [comment]
I have many Android devices, the phone I am currently testing PS on is running Android version 9. If I use an app like "File manager +" and try to open the same file off my server...meaning the file is sitting on a network share, accessed via SMB, it takes maybe 30 seconds to load. It is a 33 MB file. I am not sure if the actual network transfer of that file is taking that long or the file conversion done by Android is taking that long.
In contrast, if I open the same file on my Windows 10 PC (off the network server)...it takes 1-2 seconds. I open that file in a software called Irfanview.

The tablet I would really like PS to work on is really Samsung model. It is running Android 6.0.1. To be honest, PS does work on that tablet, but it takes over a minute to load a .dng file. That is why I requested you for this enhancement, hoping to speed up the slide show on that tablet.

**Comment by mvysny** [comment]
In the testing file you sent me, the thumbnail preview image is of size 18 MB, therefore if the network is the bottleneck, we will most probably not observe any speedup. However, it could be that Android is unable to load the RAW, which makes PhotoCloud fall back to the native Libraw library which is quite slow. In such case a speedup should be clearly visible.

I've added a preference setting "Filters/Moments / Try loading thumbnails from RAWs" which activates the thumbnail loading. Try to enable it on your device and let me know whether it helped :+1: 

Implemented in PhotoCloud 1.13.18.

**Comment by rajdude** [comment]
Hi Martin,
Thanks for looking into this. I do not think the network is the bottleneck in my home. I have a pretty good wi-fi setup here. 
I have created a video to demonstrate the difference in the time taken for Photo Cloud to download and display a photo and a file manager app to display the same photo, in my phone. Please take a look at the video here:

https://youtu.be/b9d8ygulFj8

**Points to notice:**
Starting at video time 0:35, the file copy starts and ends at 0:44. So the file took 10 seconds to transfer from my server to my phone. The size of that file is 36 MB. Notice how the "File manager +" app shows the image almost immediately.

Starting at video time 1:26, Photo Cloud starts transferring the same file. Ends at 2:22 with PS showing the file on the phone’s screen. So that is around 56 seconds.

10 seconds vs 56 seconds….that is a significant difference. Now, is it the transfer time or PS doing some sort of file conversion, I do not know :-(


By the way, when is  PhotoCloud 1.13.18 being released to the Google Play Store? It still shows  PhotoCloud 1.13.17 to me here in USA.

**Comment by mvysny** [comment]
I've released PhotoCloud 1.14 yesterday but it's under review by Google.

Thanks for sharing the video - there's definitely something wrong going there. What PhotoCloud does is that it basically downloads the video locally, then loads it into memory as a displayable bitmap. The download shouldn't take more than 10 seconds; could it be that PhotoCloud spends 46 seconds loading the RAW? Depends on your Android version - if it's 7+ then it should be able to open the RAW natively fast; however on lower Androids I'm using Libraw which might be slower... but 46 seconds sounds a lot.

Anyways, please let me know whether the "RAW thumbnails" will save the day.

**Comment by rajdude** [comment]
Martin,
I think it is a combination of Android and PhotoCloud which is taking that long to decode that file. I did more testing and I see "File Manager +" app takes around 25 seconds for similar sized files, provided it is the very first time I am opening a file off my server. Subsequent file open times are almost instantaneous, pointing to some sort of caching in the either Android or inside "File Manager +" app. Note 25 seconds is still much less than the 56 seconds Photocloud is taking.

Lets hope that the new option resolves this issue :-)

PS: that phone in the video is running Android 9, I showed the version in the video, right at the end.

**Comment by mvysny** [comment]
Hi, have you perhaps found the time to test the new thumbnail loader? Does it work better please?

**Comment by rajdude** [comment]
Oh, has Google released the new version of your app?
Let me check...

⁣
-Raj
(Sent from my cellphone)

Get BlueMail for Android ​

**Comment by rajdude** [comment]
sorry for the delay in responding, Martin...here are the results of my testing with the new version of your app (with thumbnail option in it):

I used the exact same .dng file sitting on my server on the network. I am listing loading times below as tested on two different devices using two different SMB protocols.

First, some notes : 

- I noticed that you implemented SMB 3.0 so I tried using it also.
- Browsing files using SMB 3.0 inside PhotoCloud is extremely slow. For example, sometimes it takes over 30 seconds just to enumerate/display the contents of a folder, which has lots of image files. Same problem is NOT there if I use SMB 1.0. Second time I go into the same folder, contents appear almost immediately. Maybe some caching is happening. This problem is NOT there if I use FileManager+
- Display of images is much much faster over SMB 3.0


Anyway here are the results:

**On my super old Samsung Note 3 tablet**
(this is the primary device where I would like PS to work)
Over SMB 1.0; more on this later:

With thumbnail loading disabled: 1:07 min
With thumbnail loading enabled: 0:56 min

A 16.4% decrease in loading time.

**On my Sony Xperia XZ2 compact phone**
_Over SMB 1.0_

With thumbnail loading disabled: 29 seconds
With thumbnail loading disabled: 29 seconds

no change

_Over SMB 3.0_

With thumbnail loading disabled: 3 seconds
With thumbnail loading disabled: 3 seconds

no change

**Observations:**

- So it seems to me that yes, the thumbnail loading does make a slight improvement, but it is only noticeable on my old device which is unable to do SMB3.0 for some reason using PhotoCloud. An error happens...shown below

- SMB 3.0 works so much faster on the newer phone, that thumbnail loading makes no noticeable difference. So maybe using SMB 3.0 is the "holy grail" instead of attempting to load the jpeg thumbnail in a dng file ! :-)


Here is what I would like to request next:
Is it possible to resolve this error, happening while trying to connect to my server from the old tablet:

![IMG_20201210_112830](https://user-images.githubusercontent.com/44186620/101815991-68371580-3aee-11eb-9b22-af823c94cfe2.png)

**Comment by rajdude** [comment]
oh by the way, that tablet where the error is happening while trying to use SMB 3.0 is very old, running Android 6.0.1.
It is unusable as a tablet, but works perfectly as a photo frame....just that image loading is super slow...over one minute to load a dng.

**Comment by mvysny** [comment]
Hi Rajdude, thanks for letting me know! Please see the answers below.

> Browsing files using SMB 3.0 inside PhotoCloud is extremely slow. For example, sometimes it takes over 30 seconds just to enumerate/display the contents of a folder, which has lots of image files. Same problem is NOT there if I use SMB 1.0. Second time I go into the same folder, contents appear almost immediately. Maybe some caching is happening. 

Huh that's weird. The [smbj](https://github.com/hierynomus/smbj) library is ued for SMB 2/3; sounds like there's some kind of caching or other issue in the library itself. I've checked the list of [smbj issues](https://github.com/hierynomus/smbj/issues) but nothing apparent jumped there...

> This problem is NOT there if I use FileManager+

It can be that FileManager+ uses some kind of native Samba client perhaps, which seems to be working the best. At least VLC for Android uses native samba client and it works excellent. Perhaps this is something I should investigate in.

> With thumbnail loading disabled: 1:07 min; With thumbnail loading enabled: 0:56 min; A 16.4% decrease in loading time.

Looks like the thumbnail loader have not helped that much...

> An error happens...shown below

Uh-oh. smbj uses Java 8 features (closures) and I had to enable some kind of special compilation, outlined in https://stackoverflow.com/questions/59448845/no-static-method-metafactory. Perhaps I've missed something out. Could you open a new bug report regarding this, and I'll investigate this further.

> So maybe using SMB 3.0 is the "holy grail" instead of attempting to load the jpeg thumbnail in a dng file ! :-)

Haha, yes, certainly looks like it. The difference of 29 seconds vs 3 seconds is absolutely ground-breaking.
However, PhotoCloud caches the photos on the tablet locally as JPEGs; displaying cached images in a second pass should be instantenous. Could you verify that `Settings / Cache / Photo Cache` is enabled and the Cache Size is set to 1 GB or more?
