### ISSUE TITLE
Show EXIF info in Daydream

### ISSUE THREAD

**Issue by qrpory** [mvysny/photocloud-frame-slideshow#144]
Hi,
If I manually choose "Play all streams" then selected EXIF information is shown in the bottom left corner.  When the slideshow starts automatically from Daydream the information is not displayed.
Should it use the same setting?
Android TV box.

**Comment by mvysny** [comment]
Sounds like a bug since the same HUD (heads-up display, showing e.g. EXIF, clock and/or weather forecast) should be shown, both when you start the slideshow manually and when it's started as a Daydream/Screensaver. I've just tried it and it works for me. Could you please attach a screenshot on your device, what exactly are you missing please?

**Comment by qrpory** [comment]
Hi,
I've attached a photo showing the EXIF data when I run the slideshow manually and another that doesn't show any info when it starts automatically after inactivity. 
I should also state the the TV box is probably stock android (10) rather than Android TV.  The device name was set to Pixel 2 by default.

![IMG_20201116_204225](https://user-images.githubusercontent.com/74466167/99307306-36fc5a00-284e-11eb-8b01-c9fe8219dc9b.jpg)
![IMG_20201116_204749](https://user-images.githubusercontent.com/74466167/99307320-3c59a480-284e-11eb-8d7f-890d96165692.jpg)

**Comment by mvysny** [comment]
Thank you :+1: Could you please go into Settings / Slideshow / Daydream/Screensaver / Show EXIF in Daydream and make sure it's on?

Side note: sounds weird that the Daydream EXIF setting is located in Slideshow while the Slideshow's EXIF setting is located in Widgets/HUD. I'll move the Daydream settings to Widgets/HUD.

**Comment by qrpory** [comment]
Hi.  Confirmed that Daydream is in Widgets/HUD and once enabled problem is now resolved.  Thankyou.
