### ISSUE TITLE
Timer does not work (or I need instructions)

### ISSUE THREAD

**Issue by fjrrider** [mvysny/photocloud-frame-slideshow#169]
Hello,

I have my digital photo frame running successfully, pulling images from a shared Google Photos folder.  However, I am unable to get the timer to work, or I am unclear on what it is supposed to do.  My expectation is that it would turn off the display outside the selected hours and begin again during the scheduled operational time.  Please advise if there is a bug, or if my expectations are wrong, or if there are instructions on how to properly set the timer.

Thank you,
Tom

**Comment by mvysny** [comment]
Hi, by "Timer" are you perhaps referring to the Brightness settings, and the "Start of the Day" and "End of the Day" settings?

**Comment by fjrrider** [comment]
Thank you, this makes sense.  I'll make a point of checking this and opening a new case if there is really an issue.

Tom
