### ISSUE TITLE
Is Fullscreen mode possible?

### ISSUE THREAD

**Issue by TootsMcGoots** [mvysny/photocloud-frame-slideshow#170]
Hello
Is it possible to enable a mode that hides the OS status bar at the top and soft buttons at the bottom(fire tablet)?

What is daydream mode its not described anywhere?

**Comment by mvysny** [comment]
Hi,

PhotoCloud is actually hiding the OS status bar and the buttons as well, using a standard Android API. Perhaps for some reason this doesn't work on Fire Tablet? Maybe you need to allow PhotoCloud to go full screen on your tablet - I'm guessing some kind of permission issue?

> What is daydream mode its not described anywhere?

Thanks for letting me know, I've updated https://www.android-photo-frame.eu/ to also include info on Daydream.
