### ISSUE TITLE
AndroidTV OS 12 - ADB command for ambient mode?

### ISSUE THREAD

**Issue by julianquandt** [mvysny/photocloud-frame-slideshow#179]
Hi Martin,

First of all: Thanks for developing this app, I really like it and it works great. 

The only problem that I am having currently is that AndroidTV OS 12  on my CCwGTV does not allow me to set this (or any) app to be used in ambient mode anymore, which might be a bug, but could also be a feature given that google is trying to push commercials in ambient mode apparently.

As it seems to be currently unknown when and if it will be possible to use custom ambient apps again, I was wondering whether it is possible to run the app as screensaver using an ADB command in developer mode (like mentioned here: https://stackoverflow.com/questions/73219009/settings-to-set-a-screen-saver-are-not-showing-on-google-chromecast) and if so, whether you could let me know which command to run. 

Thanks in advance.

Best,
Julian

**Comment by mvysny** [comment]
Hi Julian, thank you so much, I'm happy to hear that the app works for you well.

At the moment PhotoCloud uses the official way: it exposes the `android.service.dreams.DreamService` action of its `frame.DaydreamService` service. It works on phones, but apparently doesn't work on your TV properly, so a workaround may be necessary.

I do not know what the Ambient mode is, but the issue you linked refers to Daydream as well, so I assume it's the same thing.
However, I'm at loss on how the ticket is helpful in your situation. The question is from a developer trying to start the Daydream programmatically, while in your case you'd like to start the Daydream by the OS... However, if you can run `adb` then you can start PhotoCloud using adb the following way:
```
adb shell am start -a "sk.baka.photoframe.START_SLIDESHOW"
```
Also see https://www.android-photo-frame.eu/faq.html, the "Tasker" question.

Please let me know whether this helps.

**Comment by julianquandt** [comment]
Hi Martin,

Thanks for the quick reply and sorry for not clarifying the problem enough. 
Ambient mode is indeed the same as Daydream afaik. My problem is that I can still start the slideshow manually through the app, which is easy enough to do, but since the latest AndroidTV OS update, there is no way to set it as a screensaver anymore / use the Daydream service, which is probably an active decision by google to not allow other screensavers anymore. I found that with another app ([AerialViews](https://github.com/theothernt/AerialViews)) , it is possible to expose the daydream service to the settings by running:

 ```adb shell settings put secure screensaver_components com.neilturner.aerialviews/.ui.screensaver.DreamActivity``` 
 
 I was wondering whether the same is possible with photocloud. I have tried a few guess-work solutions like:
 
 ```
 adb shell settings put secure screensaver_components sk.baka.photoframe.frame.DaydreamService
 ```
 
 but that did not work. Am I using the wrong command or is there another reason why this would not work in this case?
 Thanks a lot!

**Comment by mvysny** [comment]
Ah, perfect! Wow, that is some excellent underground find. I'm happy that the solution is working for you, and it's good to have it documented here in the issue tracker. Since everything seems to be working, I'll close the ticket now. Best regards and hats off for finding this solution
