### ISSUE TITLE
Error 5

### ISSUE THREAD

**Issue by DavidNidam** [mvysny/photocloud-frame-slideshow#186]
Also live view fee paid and donation fee paid error  #5 message pop up every x time while watching TV (Sony with android 10)

**Comment by mvysny** [comment]
Please see the https://www.android-photo-frame.eu/faq.html, the "Getting Billing Error #5". Could you confirm that you have the same error please?

**Comment by DavidNidam** [comment]
Hi.Thank you for applying. It is the same "....error 5 ......" notification only that:1. It is installed on Sony Android 10 TV and not my phone thus no toch screen.2. Payment has been done for both live-view and donation and processedsuccessfully - attach both receiptsDady Sent from my Samsung Galaxy smartphone.



-------- הודעה מקורית --------מאת: Martin Vysny ***@***.***> תאריך: 16.8.2023  11:39  (GMT+02:00) אל: mvysny/photocloud-frame-slideshow ***@***.***> עותק: DavidNidam ***@***.***>, Author ***@***.***> נושא: Re: [mvysny/photocloud-frame-slideshow] Error 5 (Issue #186) 
Please see the https://www.android-photo-frame.eu/faq.html, the "Getting Billing Error #5". Could you confirm that you have the same error please?

**Comment by DavidNidam** [comment]
Yep.The same user.App installed from Google play and than paid from the app settings that was redirected to Google pay.Dady Sent from my Samsung Galaxy smartphone.



-------- הודעה מקורית --------מאת: Martin Vysny ***@***.***> תאריך: 16.8.2023  16:26  (GMT+02:00) אל: mvysny/photocloud-frame-slideshow ***@***.***> עותק: DavidNidam ***@***.***>, Author ***@***.***> נושא: Re: [mvysny/photocloud-frame-slideshow] Error 5 (Issue #186) 
Thank you. Is there Google Play installed on your TV? Are you logged in on your TV with the same user which purchased both items?

**Comment by mvysny** [comment]
Unfortunately it is now known that is the cause of this. This error comes directly from Google Play, and Google doesn't offer any explanation on what went wrong. There is nothing else for us to do except to wait until Google finally provides a better API.

**Comment by mvysny** [comment]
Actually, I may have found out what's causing this. Currently I'm using an in-app-purchases library which uses Google API 3. I will need to start using Google API 6 (which requires a complete rewrite of the iap feature), but that should solve the this Error 5 error message hopefully; or it will completely break the entire payment service, I'm no longer trusting Google to do any sensible quality work, I've been disappointed in Google too many times for that.

**Comment by mvysny** [comment]
I have released new PhotoCloud 1.15.1 which uses the upgraded Billing library version 6.0.1. Hopefully that should fix the issue. If not, please feel free to reopen and let me know.
