### ISSUE TITLE
Resolved: "This client does not support the negotiated dialect"

### ISSUE THREAD

**Issue by asktoby** [mvysny/photocloud-frame-slideshow#187]
Updated my samba server and photocloud stopped working with the below error.
Resolved by removing the share from Photocloud (It was "Windows Samba Share (old)") and re-creating it in Photocloud using the option "Windows Samba Share (new)".

Fatal error: java.io.IOException: jcifs.smb.SmbException: Failed to conenct: jcifs.util.transport.TransportException jcifs.smb.SmbException: This client does not support the negotiated dialect. at jcifs.smb.SmbTransport.doConnect(SmbTransport.java:329) at cjifs.util.transport.Transport.run(Transport.java:241) at java.lang.Thread.run(Thread.java:841) at jcifs.util.transport.Transport.run(Transport.java:258) at java.lang.Thread.run(Thread.java:841)

**Comment by asktoby** [comment]
Posting this to help others. Maybe this could have been handled better with a clearer error?

**Comment by mvysny** [comment]
Thank you so much for letting us know! You're right, the error message could be clearer. I'm reopening the ticket, to implement a much clearer error message, which will guide the user to use the  "Windows Samba Share (new)" option.
