### ISSUE TITLE
While browsing, "Next-Previous" buttons on Android TV do not work

### ISSUE THREAD

**Issue by rajdude** [mvysny/photocloud-frame-slideshow#194]
Hello Martin!
Hope all is well :-) It has been years since I used your app, because the streamer I was using (Fire TV stick) just did not have the bandwidth to show my RAW files on my TV, I recently got a NVIDIA Shield TV Pro. Then I remembered your app and installed it. It works REALLY well on the Shield! So well that I just bought your daydream license to run slideshows of my photos (mostly .dng files on my local windows server via SMB). THANK YOU!

**One problem I am facing:**
When I browse my photos manually, there is no way to show the "next" or "previous" photo. When I click left or right on the steering wheel button, the screen flicks as it there was something to show on screen but was not rendered. Then it starts showing some buttons on the top right, which are not click-able using my remote.

Any fix or tips on how to manually see my photos?

-Raj

**Comment by rajdude** [comment]
I am posting this as a "workaround" for people who may have the same issue.
I found out that another app - File Manager Plus is able to connect to my home server and show photos (including dng). While using that app, the left right buttons on my TV remote work fine. It also is able to show my videos, which I keep right next to the photos.
As a bonus, if given enough time, that app shows thumbnails of .dng files also, but it does not cache the thumbnails, so next time you go to the same folder, the thumbnails take time to show up.

**Comment by mvysny** [comment]
Excellent workaround, please continue using it. Unfortunately PhotoCloud is now in maintenance and no new features will be developed. It was meant to be a slideshow app, not a generic gallery viewer app, so I never implemented the swipe-to-left-for-next-photo since that doesn't really work with the internal "plumbing" of having a stream of photos fetched from all kinds of services.

**Comment by rajdude** [comment]
Uh Oh :-( Ok I understand.
