### ISSUE TITLE
Thumbnail map - please open an enhancement report with more details.

### ISSUE THREAD

**Issue by Brun059** [mvysny/photocloud-frame-slideshow#20]
can you display a thumbnail map of the location form the pic's meta data, much like NetSlide or Cloud Photo Frame EX.Net do?
and even better, when tapping on the thumbnail map, jump to google maps (such that, unlike others, it even works and displays the location)

**Comment by mvysny** [comment]
I can parse the latlon location from the image EXIF: https://developer.android.com/reference/android/media/ExifInterface.html#TAG_GPS_LATITUDE
However I have no such photo. Can you please attach a zipped photo which include EXIF location data, so that I can test it properly?

**Comment by Brun059** [comment]
can you ping me your e-mail address, I'll then send you a link to Google drive where I placed some pics with EXF GPS.

**Comment by mvysny** [comment]
Just share one picture somewhere public please, and post a link. Or you can zip it and attach it here, directly to this issue.

**Comment by Brun059** [comment]
https://drive.google.com/drive/u/0/folders/0B57s5xPVRUVcR0xWUlFBakdmR3c 

hope it helps

**Comment by mvysny** [comment]
Thanks, implemented in 1.9
