### ISSUE TITLE
enhancement : zoom

### ISSUE THREAD

**Issue by Brun059** [mvysny/photocloud-frame-slideshow#21]
is it possible to enable zoom,
even zoom within the current screen resolution will be helpful for old eyes

even better, don't compress images. caching 5 pics forth and back is good enough, cache is cheap nowadays and bandwidth unchanged (unless it compresses on the source what's not been done when reading from SMB) , hence pics could be cached in full res.

**Comment by mvysny** [comment]
Current downscale is also there to prevent out of memory errors for Android. Often Android only allows bitmaps up to certain sizes only (say, 4096x4096); getting around that limitation is not easy and requires delicate code. However, there could be a pre-built Android component for that.

**Comment by Brun059** [comment]
With zoom I mean display full screen as you currently do - end enable pinch/zoom within the screen. It would already be great to enable zoom within 4096x4096 , even within the set screen resolution would be good (current screens are much finer than a human eye, hence it would be a value add.

**Comment by Brun059** [comment]
just enable standard pinch/zoom on the current screen, no need to up the resolution (unless you easily can ;-)

**Comment by mvysny** [comment]
Yeah, this should be actually quite easy. I'll try to grab some pinch/zoom-enabled image view off the interwebs and I'll let you know.

**Comment by Brun059** [comment]
watch out, when I slide backwards and then tab the pic to go back to full screen (removing menu bar on top and bottom) then it immediately flips forward to the most recent image. In other words,  I cannot fullscreen prev pics - and assume pinch/zoom will behave similar (and I assume zoom might work into the pic, meaning enlarging at given res)  Thanks

**Comment by mvysny** [comment]
I have little motivation to work on these bugs based on your 1 star rating.

**Comment by Brun059** [comment]
You got a 5 star from me some time ag, with a long comment… ;-)

**Comment by Brun059** [comment]
sorry, seen that playstore stored the gleaming comment - but not the star rating - corrected

**Comment by mvysny** [comment]
Hey, thanks 👍 I have some ideas about using the pinch image view component with the page view,
That way, all of those recent images could be zoomed separately. I need to play with this a bit.

**Comment by mvysny** [comment]
Implemented in 1.9.3
