### ISSUE TITLE
enhancement . custom or 2 mins delay

### ISSUE THREAD

**Issue by Brun059** [mvysny/photocloud-frame-slideshow#22]
I use the app on an older tab n the living room, continually showing "old" photos from the server, slowly cycling through.  very slowly, Can you add either custom or 2 min slideshow delay?

**Comment by mvysny** [comment]
It's easier to add a predefined set of delays. I'm thinking 1,5 min, 2 min, 3 min and 5 min perhaps.

**Comment by mvysny** [comment]
Fixed in 1.9

**Comment by Brun059** [comment]
great, thanks

**Comment by mvysny** [comment]
I was asked to add 10 minutes, 30 minutes and 60 minutes options.

**Comment by mvysny** [comment]
Added in 1.9.7
