### ISSUE TITLE
bug : random is not random

### ISSUE THREAD

**Issue by Brun059** [mvysny/photocloud-frame-slideshow#23]
Could it be that random is not true random, at least the slideshow frequently starts with the same picture (out of 12'000)  Something the other slideshow apps I'm testing don't.

Ideal random might assign a weight to each folder (and recursively its subfolders), depending on the number of pics in there and then randomly picks a picture out of it. Therefore it would even be random across an unbalanced folder tree.

**Comment by mvysny** [comment]
It is true as you say, that random is not actually a "true" random. True random would require PhotoCloud to iterate all paths, discover all photos, and only then start showing those photos in a random way. However, that would introduce a huge initial delay, which is not what we want - usually we want to display any photo as soon as possible.

To achieve that, PhotoCloud iterates root directory, then first subdirectory, etc, until it finds a photo. Thus, pictures closer to the root directory will be shown more often as the initial image.

However, the directory structure crawling continues in the background, so eventually PhotoCloud crawls all images and then it will provide a true random stream of those images.

However, every image is shown exactly once per cycle. That is, PhotoCloud will discover all images, and all images will be shown exactly once, and only after that the whole stream is repeated. Therefore, while it is true that some pictures will be picked more frequently as the first image, in the long run every image will be shown the exact number of times.

**Comment by mvysny** [comment]
Closing, please reopen if you'd like something to be changed.

**Comment by Brun059** [comment]
smart :-)
