### ISSUE TITLE
Daydream screen doesn't rotate to fit landscape mode

### ISSUE THREAD

**Issue by mvysny** [mvysny/photocloud-frame-slideshow#26]
Even if the daydream starts in horizontal mode, the screen is rotated vertically. I need to check how Google Photos deals with this.

**Comment by mvysny** [comment]
It is true that the daydream doesn't rotate on my phone; however it does rotate properly on my Nexus 10 tablet - it works properly in the landscape mode, and all of the images are properly rotated. Unfortunately there is nothing I can do - it seems that on some devices the daydream rotation has been turned off! For example Sony: https://talk.sonymobile.com/t5/Xperia-Z3/Daydream-not-rotate-screen-after-Marshmallow-update/td-p/1124073
Closing as won't fix.

**Comment by mvysny** [comment]
Just tried out the Google Photos app Daydream on my phone. As I suspected - it won't rotate either. So I guess it is not possible after all - if your device decides to not to rotate the daydream, then there is nothing I can do.

**Comment by monigarr** [comment]
Google Daydream is no longer properly landscape on my Google Pixel phone.  Google Daydream is properly landscape on all our other phones (samsung s8, etc).
