### ISSUE TITLE
Bug : File information does not change when scrolling backwards

### ISSUE THREAD

**Issue by Brun059** [mvysny/photocloud-frame-slideshow#27]
Great job with the Geolocation tag 👍 
one small bug though : file information does not change when flipping pics back (sliding backwards), it remains for the  most recent pic in the slideshow.

**Comment by mvysny** [comment]
Hey, thanks! ;) Yeah, I kinda forgot about that. Good catch. I also think that the 'share' button doesn't work as well and always shares the most recent image.

**Comment by mvysny** [comment]
Fixed in 1.9.2
