### ISSUE TITLE
Add slideshow photo transition effect.

### ISSUE THREAD

**Issue by JesperJanssen** [mvysny/photocloud-frame-slideshow#29]
V 1.9.3

Maybe a possibly improvement of the app in the future.

Add an option for (different) transition effects for photo's. (For example fade in fade out, rotate out etc.)
Or add an option to let it slowly zoom in the photo (only usable if you run the slideshow with short delay times). Like Google photo's does on their daydream/screensaver mode.

**Comment by mvysny** [comment]
I have implemented a very simple transition effects for starters. Slow fly-by is harder to do, perhaps later. Fixed in 1.9.4

**Comment by JesperJanssen** [comment]
Works great :)
