### ISSUE TITLE
Increase EXIF display box when displayed horizontal

### ISSUE THREAD

**Issue by JesperJanssen** [mvysny/photocloud-frame-slideshow#30]
Just tested version 1.9.4 and it's a very good update. 

Is it possible to increase the EXIF display box in the slideshow when it is in horizontal mode since there will be more space then. In this way the full folder names and location will fit more often in the box.

On my phone the folder name is only max 20 characters long. Or will there fit more characters on a tablet as on a phone?

The translation of the GPS coordinates is great. Most of the time they are translated correctly to the city and country. Sometimes it displays the road (instead of city) and country but this is probably due to the way the api for translating coordinates to location works.

Ps. In the settings menu you still say file name in the EXIF option but this is not displayed anymore.

**Comment by mvysny** [comment]
> Ps. In the settings menu you still say file name in the EXIF option but this is not displayed anymore.

Thanks, fixed.

> Is it possible to increase the EXIF display box in the slideshow when it is in horizontal mode since there will be more space then. In this way the full folder names and location will fit more often in the box.

Yeah. Currently it is always 180dp wide; I can make it larger on larger screen/horizontal, say, up to 260dp (nearly two times the size). Let me experiment; I'll post the screenshot.

> Sometimes it displays the road (instead of city) and country but this is probably due to the way the api for translating coordinates to location works.

Yup, I only take what Google is returning to me. And the algorithm is Google-proprietary and things are computed on Google's server, so there is nothing I can do.

**Comment by mvysny** [comment]
![landscape](https://user-images.githubusercontent.com/254091/28310581-933e8bb6-6bb5-11e7-91a0-7cd6824419f0.jpg)
This is my phone in landscape mode; let me know if the box is too large or is it enough. The box will be much smaller on tablets since this is the top size and it doesn't grow with screen size. My phone's 5".

**Comment by JesperJanssen** [comment]
I think this is perfect. Thanks!

**Comment by mvysny** [comment]
Oh man, I'm overworked :-) It's 260dp now.

**Comment by JesperJanssen** [comment]
Bought a tablet today so I can so some more testing when it arrives. But first I need to buy the app again since I will be using the tablet with my family account. So another 8 euro and a 5* rating for you ;)

**Comment by mvysny** [comment]
Thank you very much, I hope the app will serve you well
