### ISSUE TITLE
Deleting OneDrive folders which need to be displayed does not work

### ISSUE THREAD

**Issue by JesperJanssen** [mvysny/photocloud-frame-slideshow#31]
V 1.9.5

I had selected multiple OneDrive folders to rootstream which works great. However, when using the trashbin icon to delete one of the selected folders to root stream it is not working. The photos of the deleted folder are still being displayed. The only option to make a new selection is to delete my OneDrive account in photocloud frame slideshow and add all the root stream folders again.

**Comment by mvysny** [comment]
I am very sorry for this behavior. I can't look at it right now; can you however check whether clearing the cache in settings after the root removal helps?

**Comment by JesperJanssen** [comment]
Clearing the cache after removing the folder from the root stream does not help. Once I cleared the cache and go back go my OneDrive folder I see all folders again (including the one I just deleted).

Ps: I have my domtica setup almost ready. Will post a picture/video once it is finished

**Comment by mvysny** [comment]
I'm a bit confused - do you mean slideshow or the browser? The browser will show all folders, regardless of which roots you have configured. The slideshow on the other hand must honor the roots list setting.
I'm on vacation right now, desperately trying to forget that computers exist :-) once I get back I'll look into this

**Comment by JesperJanssen** [comment]
I do mean the roots list setting for the slideshow. Once a folder is added you can't delete it from the list anymore.

Enjoy your holiday!

**Comment by mvysny** [comment]
Thanks! I have reproduced the issue, I'll fix it

**Comment by mvysny** [comment]
Fixed in 1.9.6
