### ISSUE TITLE
Issue with OneDrive photo's after update to version 1.9.6

### ISSUE THREAD

**Issue by JesperJanssen** [mvysny/photocloud-frame-slideshow#33]
After the update to version 1.9.6 I get the following error:

![20170811_100835](https://user-images.githubusercontent.com/17165733/29205542-dc80beae-7e7d-11e7-965e-0d3d6c682012.jpg)

I already tried clearing the cache and deleting all the data from the app (which made me adding my OneDrive account again) but that didn't solve the problem.

**Comment by JesperJanssen** [comment]
Uninstalling and re-installing the app did also not fix this issue.

I also noticed that another error message was shown very briefly before the one shown above but I'm not able to take a picture of that one since it is only up for less than a second.

**Comment by mvysny** [comment]
Holy crap, I'm so sorry about that. Yet I have not touched the OneDrive client, so I am totally at loss on what's happening here. I hope I will receive the crash information soon; you can speed things up by attaching your phone to your laptop and acquiring the error stacktrace.

**Comment by JesperJanssen** [comment]
Just read the following News article:
https://www.computing.co.uk/ctg/news/3015553/onedrive-down-were-having-issues-admits-microsoft

So perhaps this is causing the problem.

**Comment by mvysny** [comment]
Oh ok then, let's wait until Microsoft fixes their cloud.

**Comment by mvysny** [comment]
Please let me know once the situation changes, Ms fixes the cloud and hopefully things start to work again

**Comment by JesperJanssen** [comment]
Yesterday and today everything seems to work again. It was a MS problem instead of an update to v 1.9.6 problem. The MS problems just happened to start at the same time as the update to v 1.9.6

**Comment by mvysny** [comment]
Awesome, that's good to hear.
