### ISSUE TITLE
Add raw-support

### ISSUE THREAD

**Issue by Dax88** [mvysny/photocloud-frame-slideshow#34]
Please add raw-image-support (for example .cr2). I think every raw-image contains a jpeg-thumpnail (with the half resolution) - perhaps you can use this one?

**Comment by mvysny** [comment]
Thanks for letting me know. Afaik there are 4 or so raw image formats, so I guess I need to use some kind of a raw image parsing library. Let me discover one.

**Comment by mvysny** [comment]
Can you please attach just one RAW image which works for you, so that I can test the code on a real-world raw image? Thanks!

**Comment by Dax88** [comment]
I hope this one is ok for you!
[raw.zip](https://github.com/mvysny/photocloud-frame-slideshow/files/1271048/raw.zip)

**Comment by mvysny** [comment]
Thanks, I'll try the image and I'll let you know!
Just a house-keeping: I can use one of the following Android libraw ports:

1. https://github.com/TSGames/Libraw-Android
2. https://github.com/android-ports/libraw

**Comment by mvysny** [comment]
First thing to look after is that whether those raw-loading libraries has support for descaling image on-the-go. If not, that's a big problem since Android only provides limited memory to the apps and loading the whole RAW into memory (even for rescaling) would almost certainly end up in app crash with OutOfMemoryError.

**Comment by Dax88** [comment]
That sounds reasonable.

**Comment by mvysny** [comment]
Well this is unexpected: Android by default actually can open RAW CR2 images by standard means! This means no special library required! Do you please perhaps have RAW images of other types, so that I can test?

**Comment by mvysny** [comment]
Ok, Android 7 can do that, while my older phone with Android 5.1 can't load it. However, the libraw library works properly and I can use it as a fallback. Quite nice. I'd still like to test on other raw formats as well.

**Comment by mvysny** [comment]
PhotoCloud should support all raws that are supported by libraw: https://www.libraw.org/ 

crw, cr2, nef, raf, dng

**Comment by Dax88** [comment]
Sounds great! Sry i only have .cr2-images so i can't send you other image-types...

**Comment by mvysny** [comment]
No worries. I have found a site with other CRW/CR2 images so I'm going to test those; as for other types, I'll just hope that the libraw library does its thing and those raws work - if they don't, just create a new bug report ;)

**Comment by mvysny** [comment]
Implemented in 1.9.7

**Comment by Dax88** [comment]
Just quick tested it on my Galaxy S6 Edge (Android 7.0) - doesn't work :(
File 201708...cr2 is not an image, cannot show

**Comment by mvysny** [comment]
Please enable support for RAWs in Settings / Slideshow / Advanced / Include RAWs in Slideshow.
