### ISSUE TITLE
Add support for dimming at night

### ISSUE THREAD

**Issue by mvysny** [mvysny/photocloud-frame-slideshow#4]
Would like to have scheduling options for dimming/blanking at night.

**Comment by mvysny** [comment]
Sure, that's a great idea! Perhaps this should be off by default, but when activated, PhotoCloud would control the dimming of the device. I'm thinking two (or three) configuration options:
- the brightness at day, in percentages (0%, 10%, 20%, ..., 90%, 100%)
- the brightness at night, in percentages (0%, 10%, 20%, ..., 90%, 100%)
- maybe the night should be hard preset to 10pm-6am but maybe this should be user-configurable?

**Comment by mouser2017** [comment]
As far as "blanking," 0% as an option would probably be sufficient.  I'm thinking it would be nice to just have a way to "turn off" the display at night. 

I would think "night" should be user configurable if at all possible.  Start/End times would probably be sufficient.

**Comment by mvysny** [comment]
Sure, thanks for the idea. I'll see what I can do.

**Comment by mvysny** [comment]
Added Settings / Slideshow / Screen Brightness. You'll need to enable the "Control Screen Brightness" first, then optionally change other settings. You can configure:

1. brightness during the day/night
2. day start-end range

Fixed in 1.7.30

**Comment by theQuicker1** [comment]
Here I go commenting on closed issues again.

>As far as "blanking," 0% as an option would probably be sufficient. I'm thinking it would be nice to just have a way to "turn off" the display at night.

On two different tablets I have used, 0% does not turn off the backlight. It just dims it.
The way I get my frame to turn off at night is to use a "Christmas tree light" timer that turns off the electricity to the frame during the night. Using the auto-start/auto-stop on power connect/disconnect settings, the tablet display just times itself out when the slideshow stops. When the timer turns the power on again, the slideshow starts.

I'm sure it is possible to add a setting to stop the slideshow at a certain _time_ (e.g. night).  But is it possible to add a setting that wakes up the tablet and starts the slideshow again at a certain time (e.g. morning)?

**Comment by mvysny** [comment]
Yes. The dim is just to decrease the intensity of the brightness during the evening. However, setting the intensity to 0% would still continue the slideshow. Completely stopping a slideshow at some point and starting it/waking up the tablet in another is a completely new feature - please open a new feature request for that.
