### ISSUE TITLE
Start Slideshow activity

### ISSUE THREAD

**Issue by nascentt** [mvysny/photocloud-frame-slideshow#46]
I'd love a StartSlideshow activity that could be called from tasker/nova activity shortcuts to loaunch the app straight into the default slideshow.  I know there's a launch on start and a daydream, but my tablet doesnt have daydream support and I wanted to replcaite it with a tasker profile that runs the slideshow on idle.  Additionally I want to start the slideshow at a certain time and stop it at a certain time (morning/evening).

Would be very much appreciated

**Comment by mvysny** [comment]
Hi, sure. Please try to tell the Tasker to send the `sk.baka.photoframe.START_SLIDESHOW` intent action to the `PowerConnectedBroadcastReceiver` receiver located in the PhotoCloud app. Or just simply broadcast it to all apps - only PhotoCloud should catch it and start the slideshow accordingly.

Please, if this worked for you, could you post a very simple manual how you configured the Tasker itself, to run PhotoCloud?

**Comment by nascentt** [comment]
Thank you so much, this worked great.  To be honest really had no idea what you were telling me to do with sending intents, but after playing around for a while I found Tasker- Send Intent action (Tasks -> Action -> Misc -> Send Intent) :


In terms of walkthrough it was actually straightforward. I just used taker to:

add Event: Device Idle"
add Task: "Send Intent" and put "sk.baka.photoframe.START_SLIDESHOW"
and that was enough.  I couldn't figure out how to change the receiver as it was a locked dropdown list, but I left it at default and it worked.

**Comment by mvysny** [comment]
Awesome, thanks! I guess that when no particular receiver is selected, Tasker will just broadcast that intent to all apps; only the PhotoCloud app will catch it and react accordingly.

Thanks for the tutorial.

Closing as resolved.

**Comment by theQuicker1** [comment]
Thanks for the tip.  Unfortunately, this works great on my phone, but not at all on the tablet I want it to work on :(

**Comment by mvysny** [comment]
PhotoCloud now introduces two launcher icons. Please see #51 for more details.
