### ISSUE TITLE
Default to play slideshow on app open

### ISSUE THREAD

**Issue by theQuicker1** [mvysny/photocloud-frame-slideshow#51]
As a photo frame app, it seems like the default mode should be playing a slideshow if one has previously been set up.  From there, you can tap to get to the settings button or setup screen.

This will make it easier to use for grandparents who don't understand technology. They can tap the app icon and everything just works, rather than having to remember how to start a slideshow.

(Note: This would be a major interaction change to the app that might upset some people who are used to the current operation.)

**Comment by mvysny** [comment]
Hi, thanks for letting me know. You're right - that makes sense. I'll look into this.

You can use two workarounds in the meantime:
1. To start a slideshow, you can try out any Tasker app for Android, and just make sure it broadcasts the `sk.baka.photoframe.START_SLIDESHOW` intent. More on this here: #46 
2. You can also configure PhotoCloud as a Daydream service for your phone; then you can use the [Daydream Starter App](https://play.google.com/store/apps/details?id=com.brianco.daydreamlauncher&hl=en) to start the daydream by a single click.

**Comment by mvysny** [comment]
![ic_launcher](https://user-images.githubusercontent.com/254091/34034798-9e923b5e-e188-11e7-89c9-59f713a4bbdc.png)
Launches the PhotoCloud app exactly as before

![slideshow_launcher](https://user-images.githubusercontent.com/254091/34034799-9eaf3ce0-e188-11e7-9b5e-f5da8024ca08.png)
Launches just the Slideshow. By default shows all Streams (takes Stream Roots into consideration); you can override this in Settings / Slideshow / Auto-start Stream List.

**Comment by theQuicker1** [comment]
I never said thank you for adding this! It works perfectly and is exactly what I was wanting. Thank you!

**Comment by mvysny** [comment]
Happy to hear that :)
