### ISSUE TITLE
Add support for Google Photos

### ISSUE THREAD

**Issue by theQuicker1** [mvysny/photocloud-frame-slideshow#52]
Google Photos being one of the most popular personal photo repositories these days would be the perfect integration for an app like this.  Probably the best thing to do would be to add/access individual albums, rather than all the pictures in Google Photos.  I don't know how any of that works though.

Right now I am sharing photos from Google Photos to Google Drive.  Being able to remove this step (and the extra Google Drive app on my phone) would be great!

**Comment by mvysny** [comment]
Thanks for letting me know! The Google Data API client library is exceptionally crappy, so I'll check whether this is actually feasible.

**Comment by mvysny** [comment]
GData is pure crap: https://developers.google.com/gdata/articles/java_client_lib
1. It uses Ant, it's not Gradle
2. Servlet? Why the hell would it require servlets???
Unmaintained: https://github.com/google/gdata-java-client last commit 3 years ago.
The documentation is verbose but entirely deprecated - it uses Maven (Android never used Maven officially, it used Ant and then Gradle with Android Studio)
Googling for Google Photos shows recommendations to use Google Picasa Web Albums which uses obsolete crap API. Trying to use the official `com.google.apis` from Google yields results featuring old crap.

I'm sorry but I don't have the will power, time and most importantly, any desire to crawl through this Google garbage.

**Comment by mvysny** [comment]
More crap from Google. Googling `com.google.apis` returns this crap:

1. https://developers.google.com/android/guides/setup - it's just client for Google Play, no Photos support, useless.
2. https://github.com/google/google-api-java-client - some more Google crap, no Photos, useless.
3. https://developers.google.com/api-client-library/java/ - tons of Google crap, old API, totally not clear how that crap needs to be used, useless.

**Comment by mvysny** [comment]
Finally something that looks at least slightly usable: https://developers.google.com/picasa-web/docs/3.0/developers_guide_protocol
Too bad it depends on Google Data Protocol (whatever that is) which is deprecated. Also, no sample app available, no clear instructions how to add necessary libraries to Gradle.

Pure crap and waste of time.

**Comment by mvysny** [comment]
The only usable page is this: https://developers.google.com/android/guides/setup which also apparently includes some usable library for Drive which I should use (as opposed to `com.google.apis:google-api-services-drive` which I dug out God-knows-where), but that shit works and I'm not touching that shit crap with a twenty feet stick.

**Comment by theQuicker1** [comment]
I don't blame you. I'd be worried to mess with Google Drive too since it's working great. Thanks for looking into Google Photos and trying to make it work!  I am sad it's not going to happen until Google gets its act together. I truly appreciate the effort and will keep recommending this app!

**Comment by mvysny** [comment]
I apologise for the rough tone. I'll try to look into this again when I'll have more time. Maybe I will be able to find the way to make this work. Just not now - I just want to have peaceful Christmas, unspoiled by digging into that horrible mess which is Photos API :-)

**Comment by theQuicker1** [comment]
Feel free to ignore this; I have no idea if this is helpful or not: [https://productforums.google.com/d/msg/photos/gSA0NL2cYos/LitqTRy4BQAJ](https://productforums.google.com/d/msg/photos/gSA0NL2cYos/LitqTRy4BQAJ)

**Comment by mvysny** [comment]
Thanks, that's actually quite helpful! It is using the "old and deprecated" (according to the Google guys) but apparently still very lively GData API, which apparently works. I will try to hook into this old API then.

I also found this page: https://developers.google.com/gdata/docs/directory
Quoting:
> GData version is still live. No replacement API.
That confirms that I should invest the time and look into that GData thing. Thanks!

**Comment by mvysny** [comment]
An example of how incredibly idiotic Google APIs are: #55 - it is the official way of using Google Drive, which does not support listing of all files in your folder.

I will try to hook into the old GData API.

**Comment by mvysny** [comment]
Tried GData; doesn't work for me and rejects my username/password. Could you please try? It is actually quite easy to run the client:
1. Install Java
2. Download GData samples from here: https://github.com/google/gdata-java-client (scroll to the bottom, there's link Samples)
3. Unpack the zip.
4. Put the following script into the `gdata/java/sample/photos/lib` folder: TODO
5. Download javax.mail.jar from TODO and put it into `gdata/java/deps` folder
6. Run the script: `./run`
7. It should ask for the username and password. Regardless of what I inputted, it doesn't work for me and fails with: TODO

**Comment by mvysny** [comment]
Aha, https://github.com/google/gdata-java-client/issues/451:
> setUserCredentials() uses ClientLogin, which has been deprecated since April 2012 and recently disabled. You will need to use OAuth instead.

Brilliant! There is no example on how to do that, and how to then use GData with OAuth. This is a bad joke on reverse engineering. Shame on you, Google.

**Comment by mvysny** [comment]
Nope, Google Drive just ignores the `drive.photos.readonly` scope and always browses the whole Drive. I believe I've exhausted all possible ways of access Google Photos; I am exhausted myself by looking at this crap and I declare this impossible.

**Comment by mvysny** [comment]
Could it be? An actual example to access that pile of crap: https://github.com/tedyk/google-photos-android

**Comment by mvysny** [comment]
To my surprise the app does work, but it returns 0 photos unless you link your Google Photos to your Google Drive. However, then the photos will also show up in your Google Drive and in fact you can use the Google Drive stream to see your photos!

Marking this issue as won't fix, but there is a workaround:

1. Simply follow https://support.google.com/drive/answer/6156103 : First, turn on Google Drive integration at https://photos.google.com/settings ; then open your Google Drive, Settings, Create a Google Photos folder, Done.

**Comment by theQuicker1** [comment]
![image](https://user-images.githubusercontent.com/34199441/37726543-04fd5508-2d0c-11e8-820c-0ab73ed887ab.png)
 
It appears that Drive no longer supports this feature (at least in the United States).

**Comment by mvysny** [comment]
I also am seeing this error message in my Google Drive, and the error message is a bit misleading. You still can see Photos in your Drive, it will just be attached in a different location: as a folder named `Google Photos` in the `My Drive` folder:

![screenshot from 2018-03-21 20-53-10](https://user-images.githubusercontent.com/254091/37731185-200ffaa6-2d4a-11e8-90c1-57b2d0b3b3e2.png)

**Comment by mvysny** [comment]
Hoorray! Since 1.13.13 the Google Photos are natively supported by PhotoCloud - there is no need to go through the Google Drive. I'll update the documentation.
