### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by nascentt** [mvysny/photocloud-frame-slideshow#59]
PhotoCloud would be amazing on the tv.  How about Nvidia Shield support. Not just a console, does multimedia too (effectively it's just an android tv box).

Would be great to have photocloud frame as a daydream/screensaver on the device!

Happy to help in any way to bring support.

**Comment by mvysny** [comment]
If i understand correctly, it's technically an Android TV. That is, the device (Nvidia shield) is a stand alone console which runs the app directly and is connected to the TV via HDMI cable. The apps are then controlled by the gaming controller which basically supports four directional buttons, a confirm button and a back button. 

I've been thinking about adding support for Android TV and maybe it's time to do it :)

**Comment by nascentt** [comment]
So it's a set up box, pretty similar to any other android tv settop box,
only with more powerful hardware in it.  It comes with a remote control,but
the game controlelr is an option al purchase (which I also bought) - but
default media navigation is usually done by remote control (up left down
right select), the game controller works in a similar way so effectively
can be treated as one.

The main thing about the nvidia from terms of ui, is it's stock, whereas a
lot of 3rd party devices have their own home screens, so you can
effectively treat it as stock android.

You'll probably find most of the app works with it by default, I've
installed many old android apps on android tv and had them work fine.

Think of it as an android tablet without the touchscreen and a direction
pad and select button to navigate. Some android tv devices even have remote
controllers with touchpads which makes navigation even easier.  The shield
doesnt but you can use bluetooth keyboards and mice.

**Comment by mvysny** [comment]
Thanks! I'm prototyping a support for Android TV, hopefully it will be ready soon-ish. Just a quick question - does the Nvidia Shield have means to install apps through the Google Play store?

**Comment by nascentt** [comment]
Yes it does

**Comment by mvysny** [comment]
I'm going to buy Nvidia Shield myself today so that I can test :-) Also, I have already submitted PhotoCloud TV, I just need to sort out a couple of issues with Google guys and then everything should be ready.

The current TV UI is not perfect, I'll gradually improve it. Here's the first version:

![screenshot_tv_1280x720](https://user-images.githubusercontent.com/254091/34994814-5def2d96-fadd-11e7-8d68-52b3017b3923.png)

**Comment by nascentt** [comment]
oh wow! that's great to hear, i'm sure you'll enjoy it and i am very much
looking forward to seeing your app run on it.

**Comment by mvysny** [comment]
Let's not hold our breath - Google is so far rejecting PhotoCloud TV since they claim I'm trying to use a browser on a TV... but it's allowed according to their spec, so we wait and see.

**Comment by nascentt** [comment]
Google is a very strange company sometimes.  Especially considering they
list ES File Explorer on Android TV which not only is a file explorer, but
also has a web browser.

**Comment by mvysny** [comment]
Awesome! The PhotoCloud app has been approved and you can now install it into your Android TV. Enjoy!
