### ISSUE TITLE
EXIF geolocation lookup

### ISSUE THREAD

**Issue by nascentt** [mvysny/photocloud-frame-slideshow#60]
I'll try to make this my last request for a while:
I very much like the current set up of showing the location (folder) and the time, but I can't always name the parent folder as the place they were taken, so sometimes this information gives me the name of the camera it was taken from, or the person the photo is off, or however the photo folders were organised.

It'd be great if you could read the EXIF place and do a lookup to show where that location is, from that. (perhaps as an option or a failover if the exif exists).  It'd very much be appreciated, aside from support and error messages, I feel that this is really the only functionality/ui change I can would like.

one way of accomplishing this: https://wiki.openstreetmap.org/wiki/Nominatim#Reverse_Geocoding

**Comment by mvysny** [comment]
Actually Android provides the geocoding service (it's probably using Google servers). Just make sure that `Settings / Slideshow / Show EXIF in Slideshow` is checked.

Relevant feature request where this feature has been implemented: #28

**Comment by nascentt** [comment]
I do have it ticked but it doesn't work for me, I have a feeling it's because i use a shared vpn that hits the rate limit, although I temporarily turned off the vpn and it didn't seem to affect it but maybe that's due to the cache

**Comment by mvysny** [comment]
I see the following error reported: `IOException: Geocoding failed, please look into the logs for more details! ` but there is nothing interesting in the logs...

Maybe you will have more success? Could you please try to get the logs from your device?

**Comment by nascentt** [comment]
Sure i'll look for them when I get home from work.  Is there a simple way
to export logs?

**Comment by mvysny** [comment]
It's not easy but it can be done. Please follow this tutorial: https://support.symantec.com/en_US/article.HOWTO81826.html

**Comment by nascentt** [comment]
I've spent the last few hours trying to do this but adb is unable to list
the device as the adb drivers fail to install.

**Comment by mvysny** [comment]
I'm sorry to hear that. But I'm pretty sure that the built-in Android geocoding API is tied to Google play somehow and won't work without it.

The problem with osm reverse geocoding is that they have strict rules regarding usage: https://operations.osmfoundation.org/policies/nominatim/

Quoting: one request per second. Three instances of photocloud showing one image per three seconds can break this limit, so unfortunately that's not a viable choice. The built-in Android geocoding has no usage limits, or they have a tolerant per-device limits.

**Comment by nascentt** [comment]
Pity.  Thanks for looking into it.

**Comment by mvysny** [comment]
Sorry about that. I only know of one reverse geocoding service which is not limited, and that's the Android built-in API. All others are limited unless I pay, and even then there are limits. Closing therefore as won't fix; please reopen if you find an unlimited service.
