### ISSUE TITLE
Remember "Allow Screen to Turn Off"

### ISSUE THREAD

**Issue by amingle4** [mvysny/photocloud-frame-slideshow#63]
Currently, to "Allow Screen to Turn Off", we have to toggle it after the slideshow starts each time.  It would be preferable that this setting is either remembered, or allowed to be set in the main app settings.

**Comment by mvysny** [comment]
Thanks! It is both remembered and you can change the very same setting either from the settings activity, or from the slideshow itself.

Implemented in 1.10.8

**Comment by amingle4** [comment]
Excellent - thank you for responding so quickly! I look forward to checking out the new setting.
