### ISSUE TITLE
Ability to ignore no-wifi message

### ISSUE THREAD

**Issue by theQuicker1** [mvysny/photocloud-frame-slideshow#64]
Can you add a button to hide the "WiFi is down; Warning: showing cached photos until the stream+WiFi comes back online" so that it can be turned off during a slideshow?

It could be to 'permanently ignore this message', 
or just 'ignore until slideshow is started again'.

**Comment by mvysny** [comment]
I believe a setting in the Settings to hide this message is more appropriate. Imagine that you want to start a slideshow and you don't want that message to be displayed, then you basically have to wait until the wifi goes off :)

I'll thus implement this as a configuration setting.

**Comment by mvysny** [comment]
Fixed in 1.10.8

**Comment by theQuicker1** [comment]
Perfect! Thank you :)
