### ISSUE TITLE
Add the option to modify the transition time

### ISSUE THREAD

**Issue by jankete** [mvysny/photocloud-frame-slideshow#66]
It would be nice, if the user could set a value for the duration of the transition between two picture. Now, it is a little too fast for me.

**Comment by mvysny** [comment]
Would you perhaps mean Settings / Slideshow / Slideshow Delay - the delay between the photo is shown and the transition to the new photo starts? Or do you perhaps mean the duration of the transition effect itself?

**Comment by jankete** [comment]
I mean the duration of the transition effect itself.

**Comment by mvysny** [comment]
The current duration is 300 ms. I wonder what kind of options should I provide. I guess that the duration of more than 5 seconds makes no sense, so I propose the following options:

1. 0,3 s
2. 0,6 s
3. 1 s
4. 1,5 s
5. 2 s
6. 3 s
7. 5 s

**Comment by mvysny** [comment]
Implemented in 1.11
