### ISSUE TITLE
Add some animations (like Ken Burns effect)

### ISSUE THREAD

**Issue by jankete** [mvysny/photocloud-frame-slideshow#67]
I would be lucky, if the pictures were shown with a litte animation (like Ken Burns effect).

**Comment by mvysny** [comment]
You can change the Animation in Settings / Slideshow / Slideshow Transition Effect. Thanks for the tip though, I'll try to add the Ken Burns effect.

**Comment by jankete** [comment]
I know there are some transition effects. But I'd like to see a moving picture during its showing-time. Thanks for trying.

**Comment by mvysny** [comment]
Ah, actually the Ken Burns effect should be shown *while the photo is showing*, and not as a transition effect. I guess those are two separate things.

**Comment by jankete** [comment]
That is exactly what I mean. I'd like to have this animation effect while the photo is showing, and not as a transition effect.

**Comment by mvysny** [comment]
Ken Burns effect added in PhotoCloud 1.10.11

**Comment by jankete** [comment]
Thanks for adding this, It looks really good!

But is there any chance to modify the zoom-level and the animation speed?

**Comment by mvysny** [comment]
That is currently not supported, but the default algorithm can definitely be configured. Please add a feature request for that, thanks!
