### ISSUE TITLE
Cache of dropbox deleted images.

### ISSUE THREAD

**Issue by PauloTVMID** [mvysny/photocloud-frame-slideshow#7]
I use an android box adapted to a TV named MXQ. To store the images I use only dropbox and FTP. 
The problem is, whenever it's off-line it displays images in cache, so it keeps on showing images that were already deleted from the dropbox folder.

**Comment by mvysny** [comment]
Naturally if the PhotoCloud app is offline, there is no way for the app to learn of images deleted from the Dropbox folder. Therefore, it will show locally cached images until it is back online, then it will start showing online content.

It is however true that the cache is not updated even after the device comes online. That would be the perfect solution. Unfortunately that would require the app to go through the cache and ask whether the file is still present in Dropbox, and that could potentially interfere with and slow down the slideshow itself. So the current algorithm only deletes files from the cache when:

1. there is no space left in the cache for new images, and
2. the image has not been asked for for 30 days.

This is generally good for a collection of photos that doesn't change much (images are only added and rarely deleted). Yet this is suboptimal for cases when the collection of photos changes frequently.

The quickest fix I can do is to add two settings which will:
1. allow you to configure the caching period of 30 days and set it to, say, 1 day.
2. force cache to not show images older than the above mentioned period.

This way, the images deleted from the Dropbox would be shown 1 day tops. Naturally this only applies for the offline mode - when online, the app won't show old photos. So the alternative would be to keep the device online.

**Comment by mvysny** [comment]
Implemented in PhotoFrame 1.7.33; just head to Settings / Cache / Short-Lived Cache and make sure it is enabled.
