### ISSUE TITLE
Can you add BOX cloud ?

### ISSUE THREAD

**Issue by askpolaris** [mvysny/photocloud-frame-slideshow#70]
Service url: https://www.box.com/en-gb/home
as asked

**Comment by mvysny** [comment]
Thanks! The service seems to be free and the API seems to be very well documented, I like that. Way better than the Google APIs. I'll try.

**Comment by askpolaris** [comment]
Thank you so much. 

Martin Vysny <notifications@github.com> schreef op 24 januari 2018 08:36:21 CET:
>Thanks! The service seems to be free and the API seems to be very well
>documented, I like that. Way better than the Google APIs. I'll try.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mvysny/photocloud-frame-slideshow/issues/70#issuecomment-360045772

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mvysny** [comment]
Added in PhotoCloud 1.11
