### ISSUE TITLE
DLNA support stopped working

### ISSUE THREAD

**Issue by wolfzh** [mvysny/photocloud-frame-slideshow#79]
Since one of the recent releases, browsing or showing DLNA feeds stopped working. The exception reported is the following:

org.xmlpull.v1.XmlPullParserException: undefined prefix: sec (position:START_TAG <{null}sec:dcmInfo@>2:167 in java.io.StringReader ...)

**Comment by wolfzh** [comment]
![screenshot_20180221-221619](https://user-images.githubusercontent.com/34660840/36505845-101f4c56-1755-11e8-95eb-99679cd0abac.png)

**Comment by mvysny** [comment]
I'm sorry to hear that. However, it seems that the problem is not in PhotoCloud - it seems that your DLNA server is producing an unparsable XML file. Could it be that a firmware has been upgraded on your DLNA device recently?

I have tested out my Synology diskstation DLNA integration and it works as before. Can you please try other DLNA apps whether they work or whether they are broken as well?

**Comment by wolfzh** [comment]
Hi Martin -

Thanks for your reply. I am running minidlna 1.1.2 on a raspberry pi. There 
has been no version change in quite some time. Older versions of Photocloud 
used to work with this server.

I just tried a few other DLNA clients now and they could connect to my 
server and browse fine:

I tried MediaHouse-Pro and BubbleUPnP on my Android phone and also tried my 
LG PF1500 projector. They show no sign of problems.

If you have APKs for the 1.10.x series I can try if they still work.

Cheers, Wilfried

**Comment by wolfzh** [comment]
Actually, sorry, ignore that.

I just tried various older photocloud versions going back until 1.10.3 and 
they show the same problem, so it must still somehow be related to my 
server. Maybe I have some content on it now that I didn't have in the past.

I will keep investigating

Cheers

**Comment by mvysny** [comment]
Thanks for the investigation. I also have a testing installation of linux-based DLNA server on my ubuntu server, I'll check the version and whether it is still compatible.

I have also checked whether I haven't upgraded the Android client DLNA library lately, but nope - it has been cling 2.1.1 from the very beginning.

It might be that some funky files might cause funky DLNA XML file which cling can't parse.

**Comment by wolfzh** [comment]
Yes, thanks Martin, ok.

My workaround in the meantime is to use the ssh/sftp feed type. For my 
purposes that works just as well, maybe even better than DLNA.

If you find no problem with your Ubuntu server, then please feel free to 
close the ticket.

Thanks a lot for your time and have a nice weekend

Wilfried

**Comment by mvysny** [comment]
I have set up minidlna 1.2.0+dfsg-2 on my Ubuntu 17.10 and I have failed to reproduce the issue - it works properly. That being said, it definitely may be a case that there is a bug in minidlna triggered by a particular file type, or a set of files. If you can spare the time, you can investigate which folder exactly causes this issue to happen; you can then send me the file in question and I can file a bug report for minidlna.
