### ISSUE TITLE
Customize length of filename widget

### ISSUE THREAD

**Issue by amingle4** [mvysny/photocloud-frame-slideshow#80]
Hi again Martin,

As we have used the photo frame over the last several weeks, it has become apparent that being able to customize the length of text shown in the filepath/filename widget in the bottom left is important to us.  It is overall too short, which limits its usefulness given the way we have our photos organized.  I would like to request this feature be considered in a future version.  Perhaps we could choose how many characters long it is?  Or an overall percentage width?

Thanks!

**Comment by mvysny** [comment]
Hi, currently it's based on display width, but always in range of 160..260 dp. Probably because it looked weird when it spanned more of the screen. If you'd like, I can add a configuration parameter which may increase the upper limit. Just let me know how big you want it to be? Say, twice as big as current?

**Comment by amingle4** [comment]
Twice as big as current would be great, and a variable configuration parameter to set it would be perfect.

**Comment by mvysny** [comment]
Ok I'm adding the following configuration:

File name widget size:
* 1x (normal size)
* 1,5x
* 2x
* 3x

**Comment by mvysny** [comment]
Ok, head to Settings / Widget / EXIF/File Name / Widget Maximum Width and set it to 3x. Fixed in PhotoCloud 1.11.2

**Comment by amingle4** [comment]
Thanks - I updated a couple days to the latest version, and the app is now crashing on me, so I haven't been able to test this new setting.  I'm going to try the app on a different device when I get a chance and see if it's doing it there too.

**Comment by mvysny** [comment]
Another user is also reporting an immediate crash upon boot-up. Can you please create a new issue for that, and attach the output of `adb logcat` containing the crash stacktrace please?

**Comment by amingle4** [comment]
I'd love to - but I'm not sure how to. Are there instructions somewhere explaining how to get the stacktrace?

**Comment by mvysny** [comment]
https://logmatic.io/blog/a-how-to-guide-to-debugging-with-android-logcat/

**Comment by mvysny** [comment]
Please create a new bug report for this discussion, let's stop spamming the original issue.
