### ISSUE TITLE
Billing error #6: Fatal error during API action: null

### ISSUE THREAD

**Issue by sprintberlin** [mvysny/photocloud-frame-slideshow#83]
Hi,

I can't buy the full version (remove nag screens). Tried it on three tablets (Android 5 and Android 6).

I tried to pay by paypal and with credit card (same error message).

Thanks for you help.

Regards
![screenshot_2018-03-09-16-32-48](https://user-images.githubusercontent.com/2418106/37241502-90048f32-245a-11e8-872c-a05e51f5fd0b.png)
![screenshot_2018-03-09-16-32-53](https://user-images.githubusercontent.com/2418106/37241503-9025652c-245a-11e8-9ddb-b3d42f95c70a.png)

**Comment by mvysny** [comment]
Thank you for letting me know, and I'm sorry about the issue. However the purchase process is handled entirely by Google, so it would be best to bring up this issue with Google's support.

**Comment by mvysny** [comment]
If the Google's support hints at a concrete solution I need to implement, please let me know.

**Comment by sprintberlin** [comment]
problem solved, thank you, indeed it was a problem with my google account

**Comment by Eric-Law** [comment]
> problem solved, thank you, indeed it was a problem with my google account

what problem with your google account? can you describe it, I got the same problem,and dont know how it come,thanks a lot!
