### ISSUE TITLE
500px "personal" stream

### ISSUE THREAD

**Issue by MrManor** [mvysny/photocloud-frame-slideshow#89]
Not sure if the api's from 500px allows it, but I would be really great if I could get the same stream of pictures, as I get when I log in to 500px using a browser. This stream contains pictures from my favorite photographers with some additional recommendations  based on my likes.

**Comment by mvysny** [comment]
Thanks for letting me know! If 500px exports such API then it should definitely be possible. Let me have a look.

**Comment by mvysny** [comment]
Unfortunately the following mail just came in:

> Shutting down API access. Hi there,In January, we removed public access to our API. 500px has always fostered creativity with technology, but due to shifting business priorities, we’ve now decided to shut down the API completely. This decision is part of a larger strategic shift—focusing our energy on continuing to build the world’s best photography community at 500px.com, as well as strengthening our asset protection and improving our site’s performance.As of June 15, we’ll be shutting down all access to the API, which means you will no longer be able to use it to pull images or data.Questions? Feel free to email help@500px.com.Thanks,The 500px Team

So i Guess that's it for the 500px service. Gotta remove it.

**Comment by mvysny** [comment]
Closing as won't fix.

**Comment by MrManor** [comment]
Thanks for notifying. That is really a pity and a stupid decision they made, I  think I ll have to find myself another photo community then.
