### ISSUE TITLE
Add support for HEIF image format

### ISSUE THREAD

**Issue by theQuicker1** [mvysny/photocloud-frame-slideshow#92]
Maybe this isn't possible because of everything the HEIF can contain.

**Comment by mvysny** [comment]
Looks doable: https://github.com/yohhoy/heifreader Even though I wonder if it's worth the work since Android P will support it natively: https://www.androidcentral.com/android-p-features-we-love-hdr-and-heif-support
Can you attach a sample HEIF file please, so that I can test?

**Comment by mvysny** [comment]
[screenshot.heif.zip](https://github.com/mvysny/photocloud-frame-slideshow/files/2844776/screenshot.heif.zip)
gimp 2.10 can produce HEIF images also.

**Comment by mvysny** [comment]
Tried heifreader, unfortunately it failed to read my simple heif file with
```
java.lang.RuntimeException: A cast to int has gone wrong. Please contact the mp4parser discussion group (4292411352)
```

**Comment by mvysny** [comment]
Fixed in 1.13.4

**Comment by theQuicker1** [comment]
I was really hoping this would work. Now the people in my family that have iPhones have to go through an extra step to convert their pictures to JPG before they can share them to the photo frame. Thank you for trying though! :)

**Comment by mvysny** [comment]
Unfortunately I've missed that HEIF image may have `.heic` extension as well, according to https://fileinfo.com/extension/heic . This will be fixed PhotoCloud 1.13.16.

**Comment by mvysny** [comment]
Please let me know whether your tablet is Android 21+ and whether the integration with heifreader would be interesting for you.

**Comment by mvysny** [comment]
Experimental support for HEIF/HEIC added to PhotoCloud 1.13.16. You will need to enable the support in Settings / Filters/Moments / Include HEIF/HEIC in Slideshow . This is only available for Android Lollipop and higher (API 21).
