### ISSUE TITLE
App Stopping everysingle time I click on the browse button to select the source of my photos [$50]

### ISSUE THREAD

**Issue by ChezThomas** [mvysny/photocloud-frame-slideshow#94]
Using an android tablet (Android version 4.4.2) as a photoframe (Paid Version), 
when we click on Browse (to point at the folder location), it systematically give us the "Unfortunately, Photocloud Slideshow has stopped" message.
It does that on Gallery, and I also tried on the DropBox and it gives me the same problem.
I suspect and authorisation problem ? But would wait for your reply and suggestions first.
I tried reinstalling it several times, and also factory resetting the tablet, but the problem remains.
Any idea on a potential solution ?
Thanks in advance,
T.

**Comment by mvysny** [comment]
Hmm, I'm not sure there is a way to revert to the older version. I mean, I have both the older 1.11.6 and the newest 1.13 published and available on Google Play, but I'm not sure whether Google Play allows you to pick version to be installed...
Anyway 1.13 is out, please wait a bit until Google Play updates the app on your phone.

**Comment by mvysny** [comment]
And hey, many thanks for the bounty, highly appreciated! :+1:

**Comment by ChezThomas** [comment]
More than welcome ;-) Hope it will help to keep you motivated on continuing improving this simple but very useful app 👍

**Comment by ChezThomas** [comment]
So I just check with the newly pushed version 1.13 and the problem remains.
I still get the "Unfortunatly Photocloud Slideshow has stopped" as soon as I try to click the BROWSER button or SLIDESHOW... 
Any idea on what I can do ? Or any chance to give you a remote access to it ideally ?

**Comment by ChezThomas** [comment]
I tried following the guide, but since I am on Mac, it's a different software and quite lost with it :-)
![screen shot 2018-07-19 at 5 33 12 pm](https://user-images.githubusercontent.com/37170545/42934694-51947f8c-8b7a-11e8-9fc6-3de82ddd8ba9.jpg)
(Android Studio).
Also I tried just now to submit the log report from the android tablet directlty, so not sure you received the email (should be from an email address starting with velxxxxxx...@gmail.com
![screen shot 2018-07-19 at 5 38 34 pm](https://user-images.githubusercontent.com/37170545/42934782-97fd1998-8b7a-11e8-8f15-35edafe4d133.jpg)

Lastly not sure I am doing anything wrong in my Android settings.
but I attached some photos for you to have a look.

Thanks a lot in advance.

![screen shot 2018-07-19 at 5 40 48 pm](https://user-images.githubusercontent.com/37170545/42934893-e3a0cc6e-8b7a-11e8-986e-25156627eb05.jpg)
![screen shot 2018-07-19 at 5 40 41 pm](https://user-images.githubusercontent.com/37170545/42934896-e3cb367a-8b7a-11e8-89f4-4e00328c7beb.jpg)
![screen shot 2018-07-19 at 5 41 53 pm](https://user-images.githubusercontent.com/37170545/42934973-11972ffa-8b7b-11e8-999a-8039f3a9540a.jpg)

**Comment by mvysny** [comment]
Hey thanks! Actually reporting the crash to Google helped, I have one crash reported from a device Hisense Sero8 (rk3188) - would that happen to be yours?

**Comment by mvysny** [comment]
The exception is as follows:
```
Caused by: java.io.IOException: 
  at sk.baka.android.spi.AndroidFS.check (AndroidFS.java:91)
  at sk.baka.android.spi.AndroidFS.mkdir (AndroidFS.java:137)
  at sk.baka.android.DirUtils.mkdir (DirUtils.java:58)
  at sk.baka.android.DirUtils.mkdirs (DirUtils.java:95)
  at sk.baka.photoframe.fs.FileCache.get (FileCache.java:59)
```
It seems that PhotoCloud no longer can create folders on Android 4.4. Let me test this in an emulator.

**Comment by mvysny** [comment]
Okay I've pushed another release 1.13.1, blind-fixing the issue. Please try it out and let me know whether it helped

**Comment by ChezThomas** [comment]
It works with the latest update :-)
Thanks again!
T.

**Comment by mvysny** [comment]
Awesome, I'm happy that it works for you! The problem was the missing permission WRITE_EXTERNAL_STORAGE. Even though the Android API documentation explicitly says it's not needed for Android 4.4 and higher to access app's cached files, on your Android 4.4 device the permission is needed. This is the Android fragmentation in all of its ugliness :(
Anyways, I'm happy that you can continue to use the app.

**Comment by mvysny** [comment]
ps: the Crashlytics report finally arrived after a day's delay :-D It was as we suspected - PhotoCloud was unable to create the `tmp_cache` folder because of missing `WRITE_EXTERNAL_STORAGE` permission that shouldn't have been necessary in the first place.
```
Caused by java.lang.RuntimeException: java.io.IOException: Failed to create directory '/mnt/internal_sd/Android/data/sk.baka.photoframe/cache/tmp_cache_5be18553ab2343edaece03a0d68ed933thumbnail': #13 Permission denied (cache:0775:drwxrwxr-x)
       at sk.baka.photoframe.fs.FileCache.get(FileCache.java:61)
       at sk.baka.photoframe.fsimpl.cache.ThumbnailCache.<init>(ThumbnailCache.java:53)
       at sk.baka.photoframe.stream.StreamSource.newFileSystem(StreamSource.kt:216)
       at sk.baka.photoframe.stream.StreamSource.newFileSystem$default(StreamSource.kt:203)
       at sk.baka.photoframe.frame.PhotoIterator.createIterator(PhotoIterator.kt:66)
       at sk.baka.photoframe.frame.PhotoIterator.createIterator(PhotoIterator.kt:32)
```
