### ISSUE TITLE
Purchase not restored after reinstall 

### ISSUE THREAD

**Issue by eugef66** [mvysny/photocloud-frame-slideshow#96]
Hello, I purchased a removal of nagging “please purchase” slide through in-app purchase ($3.99) in Sep 2018. Yesterday I had to reset my tablet and reinstalled PhotoCloud app from Google Play store , however my purchase was not restored and there is no options in settings to do so. The nagging slide shows randomly. Please, advice.

**Comment by mvysny** [comment]
Hi, I am sorry for your troubles. The purchase should definitely survive factory wipes of your phone. I've added more info and a troubleshooting at the FAQ page, please find it there: http://www.android-photo-frame.eu/faq.html
Let me know if that helps.

**Comment by eugef66** [comment]
Hello Martin, 
Thank you for a quick response. 
I deleted and re-installed an app and this the purchase was restored. No more “nagging picture”. Not sure what happened, but you can close this issue now. Thank you again for your support.

**Comment by mvysny** [comment]
Hi, thank you for letting me know! I'm happy that the issue has been resolved for you. It's a bit hard to debug this kind of issues remotely. At least we now have a decent FAQ in case this bug happens again :)
Best regards :+1:
